const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),DATA=process.env.DATA_PATH||path.join(__dirname,'data','licenses.json'),ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'',SESSION_SECRET=process.env.SESSION_SECRET||'';
if(process.env.NODE_ENV==='production'&&(!ADMIN_PASSWORD||SESSION_SECRET.length<32)){console.error('Configure ADMIN_PASSWORD and SESSION_SECRET (32+ chars).');process.exit(1)}
const pub=path.join(__dirname,'public'),limits=new Map(),sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex'),hmac=s=>crypto.createHmac('sha256',SESSION_SECRET||'dev-only-secret').update(s).digest('hex');
const safe=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function blank(){return {licenses:[],events:[],users:[],orders:[]}}
function load(){try{const db=JSON.parse(fs.readFileSync(DATA,'utf8'));for(const k of Object.keys(blank()))db[k]||=[];return db}catch{return blank()}}
function save(db){fs.mkdirSync(path.dirname(DATA),{recursive:true});const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA)}
function json(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>250000){reject(Error('too-large'));req.destroy()}});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(Error('invalid-json'))}});req.on('error',reject)})}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function session(req){const raw=cookies(req).ice_admin;if(!raw)return false;const [exp,sig]=raw.split('.');return Number(exp)>Date.now()&&safe(sig,hmac(exp))}
function csrf(req){return safe(req.headers['x-csrf-token'],hmac((cookies(req).ice_admin||'')+'csrf').slice(0,32))}
function rate(req,key,max=12,window=60000){const id=(req.socket.remoteAddress||'')+key,now=Date.now(),arr=(limits.get(id)||[]).filter(t=>now-t<window);arr.push(now);limits.set(id,arr);return arr.length<=max}
function duration(plan){return {d30:30,permanent:null}[plan]}
function passwordHash(password,salt){return crypto.scryptSync(password,salt,32).toString('hex')}
function issueToken(user,kind='app'){const token=crypto.randomBytes(32).toString('base64url'),key=kind==='web'?'webTokenHash':'tokenHash';user[key]=sha(token);user[kind==='web'?'webTokenIssuedAt':'tokenIssuedAt']=new Date().toISOString();return token}
function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')}
function licenseFor(db,user){return user&&db.licenses.find(x=>x.id===user.licenseId)}
function licenseStatus(l){return !l?'pending':l.revoked?'revoked':l.expiresAt&&Date.parse(l.expiresAt)<=Date.now()?'expired':'active'}
function publicAccount(user,license,token){return {ok:true,token,username:user.username,email:user.email||'',plan:license&&license.plan||'none',status:licenseStatus(license),expiresAt:license&&license.expiresAt||null,permanent:!!license&&!license.expiresAt,createdAt:user.createdAt,hardwareBound:!!(license&&license.hardwareHash),lastSeenAt:license&&license.lastSeenAt||null}}
function validateCredentials(input){const username=String(input.username||'').trim(),email=String(input.email||'').trim().toLowerCase(),password=String(input.password||'');if(!/^[a-zA-Z0-9._-]{3,24}$/.test(username))return {error:'Use de 3 a 24 caracteres no usuário.'};if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return {error:'Informe um e-mail válido.'};if(password.length<8||password.length>128)return {error:'A senha precisa ter pelo menos 8 caracteres.'};return {username,email,password}}
function createAccount(db,input){const v=validateCredentials(input);if(v.error)return {status:400,data:{ok:false,message:v.error}};if(db.users.some(x=>x.usernameLower===v.username.toLowerCase()))return {status:409,data:{ok:false,message:'Este usuário já existe.'}};if(v.email&&db.users.some(x=>x.email===v.email))return {status:409,data:{ok:false,message:'Este e-mail já está cadastrado.'}};const salt=crypto.randomBytes(16).toString('hex'),user={id:crypto.randomUUID(),username:v.username,usernameLower:v.username.toLowerCase(),email:v.email,passwordSalt:salt,passwordHash:passwordHash(v.password,salt),createdAt:new Date().toISOString()};db.users.unshift(user);db.events.unshift({at:user.createdAt,type:'customer_created',user:user.id});return {status:201,data:publicAccount(user,null,issueToken(user,'web'))}}
function checkPassword(db,input){const login=String(input.login||input.username||input.email||'').trim().toLowerCase(),user=db.users.find(x=>x.usernameLower===login||String(x.email||'').toLowerCase()===login),password=String(input.password||'');if(!user||!safe(passwordHash(password,user.passwordSalt||''),user.passwordHash))return null;return user}
function webLogin(db,input){const user=checkPassword(db,input);if(!user)return {status:401,data:{ok:false,message:'Usuário, e-mail ou senha incorretos.'}};return {status:200,data:publicAccount(user,licenseFor(db,user),issueToken(user,'web'))}}
function webProfile(db,token){const user=db.users.find(x=>x.webTokenHash&&safe(x.webTokenHash,sha(token||'')));if(!user)return {status:401,data:{ok:false,message:'Sessão expirada.'}};return {status:200,data:publicAccount(user,licenseFor(db,user),null),user}}
function simulatePurchase(db,token,plan){const auth=webProfile(db,token);if(auth.status!==200)return auth;if(duration(plan)===undefined)return {status:400,data:{ok:false,message:'Plano inválido.'}};const user=auth.user,now=new Date(),current=licenseFor(db,user),license=current||{id:crypto.randomUUID(),userId:user.id,createdAt:now.toISOString()};license.plan=plan;license.revoked=false;license.activatedAt=now.toISOString();license.expiresAt=duration(plan)?new Date(now.getTime()+duration(plan)*86400000).toISOString():null;if(!current)db.licenses.unshift(license);user.licenseId=license.id;db.events.unshift({at:now.toISOString(),type:'purchase_simulated',user:user.id,plan});return {status:200,data:{...publicAccount(user,license,null),simulated:true,download:'https://raw.githubusercontent.com/kaiquedupix-max/iceoptmizer/main/downloads/ice-optimizer.exe'}}}
function hardwareAllowed(license,input,bind=false){const device=String(input.deviceId||''),hardware=String(input.hardwareId||device);if(!hardware)return false;if(!license.hardwareHash&&bind){license.deviceHash=sha(device);license.hardwareHash=sha(hardware);license.hardwareBoundAt=new Date().toISOString();return true}return !!license.hardwareHash&&safe(license.hardwareHash,sha(hardware))}
function loginAccount(db,input){const user=checkPassword(db,input);if(!user)return {status:401,data:{ok:false,message:'Usuário ou senha incorretos.'}};const license=licenseFor(db,user),status=licenseStatus(license);if(status==='pending')return {status:402,data:{ok:false,message:'Sua conta ainda não possui uma ativação. Entre no site e simule a compra de um plano.'}};if(status==='revoked')return {status:403,data:{ok:false,message:'A ativação desta conta foi suspensa.'}};if(status==='expired')return {status:403,data:{ok:false,message:'Sua ativação expirou.'}};if(!hardwareAllowed(license,input,true))return {status:403,data:{ok:false,message:'Esta conta já está vinculada a outro computador.'}};license.lastSeenAt=new Date().toISOString();return {status:200,data:publicAccount(user,license,issueToken(user,'app'))}}
function profileByToken(db,token,input){const user=db.users.find(x=>x.tokenHash&&safe(x.tokenHash,sha(token||'')));if(!user)return {status:401,data:{ok:false,message:'Sessão inválida. Entre novamente.'}};const license=licenseFor(db,user),status=licenseStatus(license);if(status!=='active')return {status:403,data:{ok:false,message:'Ativação indisponível.'}};if(!hardwareAllowed(license,input,false))return {status:403,data:{ok:false,message:'Hardware não autorizado.'}};license.lastSeenAt=new Date().toISOString();return {status:200,data:publicAccount(user,license,null)}}
function publicCustomer(user,db){const l=licenseFor(db,user),status=licenseStatus(l);return {id:user.id,username:user.username,email:user.email||'',createdAt:user.createdAt,plan:l&&l.plan||'none',status:status==='revoked'?'suspended':status,expiresAt:l&&l.expiresAt||null,hardwareBound:!!(l&&l.hardwareHash),hardwareBoundAt:l&&l.hardwareBoundAt||null,lastSeenAt:l&&l.lastSeenAt||null}}
function staticFile(req,res,url){let file=url.pathname==='/'?'index.html':url.pathname==='/admin'?'admin.html':url.pathname.slice(1);if(file.includes('..'))return false;const full=path.join(pub,file);if(!full.startsWith(pub)||!fs.existsSync(full)||fs.statSync(full).isDirectory())return false;const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'},fresh=['.html','.css','.js'].includes(ext);res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':fresh?'no-cache':'public, max-age=3600','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});fs.createReadStream(full).pipe(res);return true}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');
 if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true});
 if(req.method==='POST'&&url.pathname==='/api/web/register'){if(!rate(req,'web-register',8,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const db=load(),result=createAccount(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/login'){if(!rate(req,'web-login',12,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const db=load(),result=webLogin(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='GET'&&url.pathname==='/api/web/profile'){const db=load(),result=webProfile(db,bearer(req));return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/simulate-purchase'){const b=await body(req),db=load(),result=simulatePurchase(db,bearer(req),String(b.plan||''));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/login'){const db=load(),result=loginAccount(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/profile'){const db=load(),result=profileByToken(db,bearer(req),await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/register')return json(res,410,{ok:false,message:'Crie sua conta pelo site do Ice Optimizer.'});
 if(req.method==='POST'&&url.pathname==='/api/admin/login'){if(!rate(req,'admin-login',6,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const b=await body(req);if(!ADMIN_PASSWORD||!safe(sha(b.password||''),sha(ADMIN_PASSWORD)))return json(res,401,{ok:false,message:'Senha incorreta.'});const exp=String(Date.now()+8*3600000),cookie=exp+'.'+hmac(exp);return json(res,200,{ok:true,csrf:hmac(cookie+'csrf').slice(0,32)},{'set-cookie':`ice_admin=${cookie}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}
 if(url.pathname.startsWith('/api/admin/')){if(!session(req))return json(res,401,{ok:false,message:'Sessão expirada.'});if(req.method!=='GET'&&!csrf(req))return json(res,403,{ok:false,message:'Atualize a página.'});const db=load();
  if(req.method==='GET'&&url.pathname==='/api/admin/customers')return json(res,200,{ok:true,csrf:hmac((cookies(req).ice_admin||'')+'csrf').slice(0,32),customers:db.users.map(u=>publicCustomer(u,db)),events:db.events.slice(0,80)});
  const m=url.pathname.match(/^\/api\/admin\/customers\/([0-9a-f-]+)\/(status|reset-hwid)$/);if(req.method==='POST'&&m){const user=db.users.find(x=>x.id===m[1]),l=licenseFor(db,user);if(!user||!l)return json(res,404,{ok:false,message:'Cliente ou ativação não encontrado.'});const b=await body(req);if(m[2]==='status')l.revoked=!b.active;else{delete l.hardwareHash;delete l.deviceHash;delete l.hardwareBoundAt}db.events.unshift({at:new Date().toISOString(),type:m[2],user:user.id});save(db);return json(res,200,{ok:true})}
 }
 if(staticFile(req,res,url))return;json(res,404,{ok:false,message:'Não encontrado.'});
 }catch(e){console.error(e);if(!res.headersSent)json(res,500,{ok:false,message:'Erro interno.'});else res.end()}});
server.listen(PORT,()=>console.log('ice optimizer portal on '+PORT));
module.exports={server,load,save,duration,createAccount,webLogin,webProfile,simulatePurchase,loginAccount,profileByToken,hardwareAllowed,publicCustomer};
