const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),DATA=process.env.DATA_PATH||path.join(__dirname,'data','licenses.json'),ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'',SESSION_SECRET=process.env.SESSION_SECRET||'',MP_ACCESS_TOKEN=process.env.MP_ACCESS_TOKEN||'',MP_PUBLIC_KEY=process.env.MP_PUBLIC_KEY||'',MP_WEBHOOK_SECRET=process.env.MP_WEBHOOK_SECRET||'',PUBLIC_URL=String(process.env.PUBLIC_URL||'').replace(/\/$/,''),AFFILIATE_HOLD_DAYS=Math.max(0,Number(process.env.AFFILIATE_HOLD_DAYS||14)),PLANS={d30:{amount:29.90,title:'Ice Optimizer Mensal'},permanent:{amount:100,title:'Otimização Completa'}};
if(process.env.NODE_ENV==='production'&&(!ADMIN_PASSWORD||SESSION_SECRET.length<32)){console.error('Configure ADMIN_PASSWORD and SESSION_SECRET (32+ chars).');process.exit(1)}
const pub=path.join(__dirname,'public'),limits=new Map(),sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex'),hmac=s=>crypto.createHmac('sha256',SESSION_SECRET||'dev-only-secret').update(s).digest('hex');
const safe=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function blank(){return {licenses:[],events:[],users:[],orders:[],partners:[],withdrawals:[]}}
function load(){try{const db=JSON.parse(fs.readFileSync(DATA,'utf8'));for(const k of Object.keys(blank()))db[k]||=[];return db}catch{return blank()}}
function save(db){fs.mkdirSync(path.dirname(DATA),{recursive:true});const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA)}
function json(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>250000){reject(Error('too-large'));req.destroy()}});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(Error('invalid-json'))}});req.on('error',reject)})}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function session(req){const raw=cookies(req).ice_admin;if(!raw)return false;const [exp,sig]=raw.split('.');return Number(exp)>Date.now()&&safe(sig,hmac(exp))}
function csrf(req){return safe(req.headers['x-csrf-token'],hmac((cookies(req).ice_admin||'')+'csrf').slice(0,32))}
function rate(req,key,max=12,window=60000){const id=(req.socket.remoteAddress||'')+key,now=Date.now(),arr=(limits.get(id)||[]).filter(t=>now-t<window);arr.push(now);limits.set(id,arr);return arr.length<=max}
function duration(plan){return {d30:30,permanent:null}[plan]}
function activatePlan(db,user,plan,source,orderId){const days=duration(plan);if(days===undefined)return null;const now=new Date(),current=licenseFor(db,user),license=current||{id:crypto.randomUUID(),userId:user.id,createdAt:now.toISOString()};license.plan=plan;license.revoked=false;license.activatedAt=now.toISOString();license.expiresAt=days?new Date(now.getTime()+days*86400000).toISOString():null;license.source=source||'admin';if(orderId)license.orderId=orderId;if(!current)db.licenses.unshift(license);user.licenseId=license.id;return license}
function passwordHash(password,salt){return crypto.scryptSync(password,salt,32).toString('hex')}
function issueToken(user,kind='app'){const token=crypto.randomBytes(32).toString('base64url'),key=kind==='web'?'webTokenHash':'tokenHash';user[key]=sha(token);user[kind==='web'?'webTokenIssuedAt':'tokenIssuedAt']=new Date().toISOString();return token}
function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')}
function licenseFor(db,user){return user&&db.licenses.find(x=>x.id===user.licenseId)}
function licenseStatus(l){return !l?'pending':l.revoked?'revoked':l.expiresAt&&Date.parse(l.expiresAt)<=Date.now()?'expired':'active'}
function publicAccount(user,license,token){return {ok:true,token,username:user.username,email:user.email||'',plan:license&&license.plan||'none',status:licenseStatus(license),expiresAt:license&&license.expiresAt||null,permanent:!!license&&!license.expiresAt,createdAt:user.createdAt,hardwareBound:!!(license&&license.hardwareHash),lastSeenAt:license&&license.lastSeenAt||null}}
function validateCredentials(input){const username=String(input.username||'').trim(),email=String(input.email||'').trim().toLowerCase(),password=String(input.password||'');if(!/^[a-zA-Z0-9._-]{3,24}$/.test(username))return {error:'Use de 3 a 24 caracteres no usuário.'};if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return {error:'Informe um e-mail válido.'};if(password.length<8||password.length>128)return {error:'A senha precisa ter pelo menos 8 caracteres.'};return {username,email,password}}
function createAccount(db,input){const v=validateCredentials(input);if(v.error)return {status:400,data:{ok:false,message:v.error}};if(db.users.some(x=>x.usernameLower===v.username.toLowerCase()))return {status:409,data:{ok:false,message:'Este usuário já existe.'}};if(v.email&&db.users.some(x=>x.email===v.email))return {status:409,data:{ok:false,message:'Este e-mail já está cadastrado.'}};const salt=crypto.randomBytes(16).toString('hex'),user={id:crypto.randomUUID(),username:v.username,usernameLower:v.username.toLowerCase(),email:v.email,passwordSalt:salt,passwordHash:passwordHash(v.password,salt),createdAt:new Date().toISOString()};db.users.unshift(user);db.events.unshift({at:user.createdAt,type:'customer_created',user:user.id});return {status:201,data:publicAccount(user,null,issueToken(user,'web'))}}
function checkPassword(db,input){const login=String(input.login||input.username||input.email||'').trim().toLowerCase(),user=db.users.find(x=>x.usernameLower===login||String(x.email||'').toLowerCase()===login),password=String(input.password||'');if(!user||!safe(passwordHash(password,user.passwordSalt||''),user.passwordHash))return null;return user}
function webLogin(db,input){const user=checkPassword(db,input);if(!user)return {status:401,data:{ok:false,message:'Usuário, e-mail ou senha incorretos.'}};return {status:200,data:publicAccount(user,licenseFor(db,user),issueToken(user,'web'))}}
function webProfile(db,token){const user=db.users.find(x=>x.webTokenHash&&safe(x.webTokenHash,sha(token||'')));if(!user)return {status:401,data:{ok:false,message:'Sessão expirada.'}};return {status:200,data:publicAccount(user,licenseFor(db,user),null),user}}
function simulatePurchase(db,token,plan){const auth=webProfile(db,token);if(auth.status!==200)return auth;if(duration(plan)===undefined)return {status:400,data:{ok:false,message:'Plano inválido.'}};const user=auth.user,license=activatePlan(db,user,plan,'simulation');db.events.unshift({at:new Date().toISOString(),type:'purchase_simulated',user:user.id,plan});return {status:200,data:{...publicAccount(user,license,null),simulated:true,download:'https://raw.githubusercontent.com/kaiquedupix-max/iceoptmizer/main/downloads/ice-optimizer.exe'}}}
function hardwareAllowed(license,input,bind=false){const device=String(input.deviceId||''),hardware=String(input.hardwareId||device);if(!hardware)return false;if(!license.hardwareHash&&bind){license.deviceHash=sha(device);license.hardwareHash=sha(hardware);license.hardwareBoundAt=new Date().toISOString();return true}return !!license.hardwareHash&&safe(license.hardwareHash,sha(hardware))}
function loginAccount(db,input){const user=checkPassword(db,input);if(!user)return {status:401,data:{ok:false,message:'Usuário ou senha incorretos.'}};const license=licenseFor(db,user),status=licenseStatus(license);if(status==='pending')return {status:402,data:{ok:false,message:'Sua conta ainda não possui uma ativação. Entre no site e finalize a compra de um plano.'}};if(status==='revoked')return {status:403,data:{ok:false,message:'A ativação desta conta foi suspensa.'}};if(status==='expired')return {status:403,data:{ok:false,message:'Sua ativação expirou.'}};if(!hardwareAllowed(license,input,true))return {status:403,data:{ok:false,message:'Esta conta já está vinculada a outro computador.'}};license.lastSeenAt=new Date().toISOString();return {status:200,data:publicAccount(user,license,issueToken(user,'app'))}}
function profileByToken(db,token,input){const user=db.users.find(x=>x.tokenHash&&safe(x.tokenHash,sha(token||'')));if(!user)return {status:401,data:{ok:false,message:'Sessão inválida. Entre novamente.'}};const license=licenseFor(db,user),status=licenseStatus(license);if(status!=='active')return {status:403,data:{ok:false,message:'Ativação indisponível.'}};if(!hardwareAllowed(license,input,false))return {status:403,data:{ok:false,message:'Hardware não autorizado.'}};license.lastSeenAt=new Date().toISOString();return {status:200,data:publicAccount(user,license,null)}}
function publicCustomer(user,db){const l=licenseFor(db,user),status=licenseStatus(l);return {id:user.id,username:user.username,email:user.email||'',createdAt:user.createdAt,plan:l&&l.plan||'none',status:status==='revoked'?'suspended':status,expiresAt:l&&l.expiresAt||null,hardwareBound:!!(l&&l.hardwareHash),hardwareBoundAt:l&&l.hardwareBoundAt||null,lastSeenAt:l&&l.lastSeenAt||null}}
function partnerByToken(db,token){return db.partners.find(x=>x.tokenHash&&safe(x.tokenHash,sha(token||'')))}
function partnerView(partner,db){const now=Date.now(),sales=db.orders.filter(x=>x.partnerId===partner.id&&x.status==='approved'),commission=sales.reduce((n,x)=>n+Number(x.commissionAmount||0),0),availableEarned=sales.filter(x=>Date.parse(x.commissionAvailableAt||0)<=now).reduce((n,x)=>n+Number(x.commissionAmount||0),0),withdrawals=db.withdrawals.filter(x=>x.partnerId===partner.id),reserved=withdrawals.filter(x=>['pending','approved','paid'].includes(x.status)).reduce((n,x)=>n+Number(x.amount||0),0),paid=withdrawals.filter(x=>x.status==='paid').reduce((n,x)=>n+Number(x.amount||0),0);return {id:partner.id,name:partner.name,email:partner.email,slug:partner.slug,status:partner.status,commissionPercent:30,pixKeyType:partner.pixKeyType||'',pixKey:partner.pixKey||'',beneficiaryName:partner.beneficiaryName||'',createdAt:partner.createdAt,sales:sales.length,revenue:sales.reduce((n,x)=>n+Number(x.amount||0),0),commission,commissionPending:Math.max(0,commission-availableEarned),balanceAvailable:Math.max(0,availableEarned-reserved),withdrawn:paid,withdrawals:withdrawals.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))}}
function slugify(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,36)}
function createPartner(db,input){const name=String(input.name||'').trim(),email=String(input.email||'').trim().toLowerCase();if(name.length<3)return {status:400,data:{ok:false,message:'Informe o nome do parceiro.'}};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return {status:400,data:{ok:false,message:'Informe um e-mail válido.'}};if(db.partners.some(x=>x.email===email))return {status:409,data:{ok:false,message:'Este parceiro já está cadastrado.'}};let slug=slugify(input.slug||name)||crypto.randomBytes(4).toString('hex');if(db.partners.some(x=>x.slug===slug))slug+='-'+crypto.randomBytes(2).toString('hex');const token=crypto.randomBytes(32).toString('base64url'),partner={id:crypto.randomUUID(),name,email,slug,tokenHash:sha(token),status:'active',commissionPercent:30,createdAt:new Date().toISOString()};db.partners.unshift(partner);db.events.unshift({at:partner.createdAt,type:'partner_created',partner:partner.id});return {status:201,data:{ok:true,partner:partnerView(partner,db),accessUrl:(PUBLIC_URL||'')+'/parceiro?token='+token,token}}}
function savePartnerPayout(db,partner,input){const type=String(input.pixKeyType||''),key=String(input.pixKey||'').trim(),name=String(input.beneficiaryName||'').trim();if(!['cpf','cnpj','email','phone','random'].includes(type))return {status:400,data:{ok:false,message:'Selecione o tipo da chave Pix.'}};if(key.length<5||key.length>140||name.length<3)return {status:400,data:{ok:false,message:'Confira o titular e a chave Pix.'}};partner.pixKeyType=type;partner.pixKey=key;partner.beneficiaryName=name;partner.updatedAt=new Date().toISOString();db.events.unshift({at:partner.updatedAt,type:'partner_payout_updated',partner:partner.id});return {status:200,data:{ok:true,partner:partnerView(partner,db)}}}
function requestWithdrawal(db,partner,input){const amount=Math.round(Number(input.amount)*100)/100,view=partnerView(partner,db);if(!partner.pixKey)return {status:400,data:{ok:false,message:'Cadastre sua chave Pix antes de solicitar o saque.'}};if(!Number.isFinite(amount)||amount<20)return {status:400,data:{ok:false,message:'O saque mínimo é R$ 20,00.'}};if(amount>view.balanceAvailable+.001)return {status:400,data:{ok:false,message:'Saldo disponível insuficiente.'}};const withdrawal={id:crypto.randomUUID(),partnerId:partner.id,amount,status:'pending',pixKeyType:partner.pixKeyType,pixKey:partner.pixKey,beneficiaryName:partner.beneficiaryName,createdAt:new Date().toISOString()};db.withdrawals.unshift(withdrawal);db.events.unshift({at:withdrawal.createdAt,type:'withdrawal_requested',partner:partner.id,withdrawal:withdrawal.id,amount});return {status:201,data:{ok:true,withdrawal,partner:partnerView(partner,db)}}}
function mpSignatureValid(headers,dataId){if(!MP_WEBHOOK_SECRET)return false;const parts=Object.fromEntries(String(headers['x-signature']||'').split(',').map(x=>x.trim().split('='))),requestId=String(headers['x-request-id']||''),id=String(dataId||'').toLowerCase();if(!parts.ts||!parts.v1||!requestId||!id)return false;return safe(parts.v1,crypto.createHmac('sha256',MP_WEBHOOK_SECRET).update(`id:${id};request-id:${requestId};ts:${parts.ts};`).digest('hex'))}
function paymentPayload(user,plan,input,partner){const product=PLANS[plan];if(!product)throw Error('Plano inválido.');const allowed=['token','installments','payment_method_id','issuer_id','payer','device_id'];const payload={transaction_amount:product.amount,description:product.title,external_reference:`ice:${user.id}:${plan}:${partner?partner.id:'direct'}`,metadata:{user_id:user.id,plan,partner_id:partner?partner.id:''},notification_url:(PUBLIC_URL||'')+'/api/webhooks/mercadopago'};for(const key of allowed)if(input[key]!==undefined)payload[key]=input[key];payload.payer={...(payload.payer||{}),email:user.email};if(!payload.payment_method_id)throw Error('Escolha uma forma de pagamento.');return payload}
async function mpRequest(route,options={}){if(!MP_ACCESS_TOKEN)throw Error('O Mercado Pago ainda não foi configurado.');const response=await fetch('https://api.mercadopago.com'+route,{...options,headers:{authorization:'Bearer '+MP_ACCESS_TOKEN,'content-type':'application/json',...(options.headers||{})}}),data=await response.json();if(!response.ok)throw Error(data.message||data.error||'O Mercado Pago não conseguiu concluir a operação.');return data}
async function createMercadoPagoPayment(user,plan,input,partner){let payload;try{payload=paymentPayload(user,plan,input,partner)}catch(e){return {status:400,data:{ok:false,message:e.message}}}try{const payment=await mpRequest('/v1/payments',{method:'POST',headers:{'x-idempotency-key':String(input.idempotencyKey||crypto.randomUUID())},body:JSON.stringify(payload)});return {status:201,paymentRaw:payment,data:{ok:true,payment:{id:payment.id,status:payment.status,statusDetail:payment.status_detail,pix:payment.point_of_interaction&&payment.point_of_interaction.transaction_data||null}}}}catch(e){return {status:502,data:{ok:false,message:e.message}}}}
function applyMercadoPagoPayment(db,payment){const meta=payment.metadata||{},user=db.users.find(x=>x.id===String(meta.user_id||'')),partner=db.partners.find(x=>x.id===String(meta.partner_id||'')),plan=String(meta.plan||''),id=String(payment.id),previous=db.orders.find(x=>x.id===id),status=String(payment.status||'');if(previous&&previous.status===status)return {ok:true,duplicate:true,activated:status==='approved'};const amount=Number(payment.transaction_amount||0),paidAt=payment.date_approved||new Date().toISOString(),availableAt=new Date(Date.parse(paidAt)+AFFILIATE_HOLD_DAYS*86400000).toISOString(),order=previous||{id,createdAt:payment.date_created||new Date().toISOString()};Object.assign(order,{status,customerEmail:payment.payer&&payment.payer.email||user&&user.email||'',partnerId:partner&&partner.id||null,amount,commissionAmount:partner?Math.round(amount*30)/100:0,commissionAvailableAt:availableAt,paidAt:status==='approved'?paidAt:null,plan:PLANS[plan]?plan:null,provider:'mercadopago'});if(!previous)db.orders.unshift(order);if(status==='approved'&&user&&PLANS[plan])activatePlan(db,user,plan,'mercadopago',id);if(['refunded','charged_back','cancelled'].includes(status)&&user){const license=licenseFor(db,user);if(license&&license.orderId===id)license.revoked=true}db.events.unshift({at:new Date().toISOString(),type:'mercadopago_'+status,order:id,user:user&&user.id||null,partner:partner&&partner.id||null});return {ok:true,activated:status==='approved'&&!!user&&!!PLANS[plan]}}
function staticFile(req,res,url){let file=url.pathname==='/'?'index.html':url.pathname==='/admin'?'admin.html':url.pathname==='/parceiro'?'partner.html':url.pathname.slice(1);if(file.includes('..'))return false;const full=path.join(pub,file);if(!full.startsWith(pub)||!fs.existsSync(full)||fs.statSync(full).isDirectory())return false;const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'},fresh=['.html','.css','.js'].includes(ext);res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':fresh?'no-cache':'public, max-age=3600','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline' https://*.mercadopago.com https://*.mercadopago.com.br https://http2.mlstatic.com; script-src 'self' https://sdk.mercadopago.com https://www.mercadopago.com; img-src 'self' data: https://*.mercadopago.com https://*.mercadopago.com.br https://http2.mlstatic.com; connect-src 'self' https://api.mercadopago.com https://*.mercadopago.com https://*.mercadopago.com.br; frame-src https://*.mercadopago.com https://*.mercadopago.com.br; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});fs.createReadStream(full).pipe(res);return true}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');
 if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true});
 if(req.method==='GET'&&url.pathname==='/api/store/config'){const db=load(),ref=cookies(req).ice_ref,partner=db.partners.find(x=>x.slug===ref&&x.status==='active');return json(res,200,{ok:true,mercadoPagoReady:!!(MP_ACCESS_TOKEN&&MP_PUBLIC_KEY&&MP_WEBHOOK_SECRET&&PUBLIC_URL),publicKey:MP_PUBLIC_KEY,partner:partner?partner.name:null,prices:{d30:PLANS.d30.amount,permanent:PLANS.permanent.amount}})}
 if(req.method==='POST'&&url.pathname==='/api/webhooks/mercadopago'){const payload=await body(req),dataId=String(url.searchParams.get('data.id')||payload.data&&payload.data.id||'');if(!mpSignatureValid(req.headers,dataId))return json(res,401,{ok:false,message:'Webhook não autorizado.'});try{const payment=await mpRequest('/v1/payments/'+encodeURIComponent(dataId)),db=load(),result=applyMercadoPagoPayment(db,payment);save(db);return json(res,200,result)}catch(e){return json(res,502,{ok:false,message:e.message})}}
 const redirect=url.pathname.match(/^\/r\/([a-z0-9-]+)$/);if(req.method==='GET'&&redirect){const db=load(),partner=db.partners.find(x=>x.slug===redirect[1]&&x.status==='active');if(!partner)return json(res,404,{ok:false,message:'Link de parceiro indisponível.'});res.writeHead(302,{location:'/?parceiro='+encodeURIComponent(partner.slug)+'#planos','set-cookie':`ice_ref=${partner.slug}; Max-Age=2592000; Path=/; HttpOnly; Secure; SameSite=Lax`,'cache-control':'no-store'});return res.end()}
 if(req.method==='GET'&&url.pathname==='/api/partner/profile'){const db=load(),partner=partnerByToken(db,bearer(req));if(!partner)return json(res,401,{ok:false,message:'Acesso de parceiro inválido.'});return json(res,200,{ok:true,partner:partnerView(partner,db),publicLink:(PUBLIC_URL||'')+'/r/'+partner.slug,holdDays:AFFILIATE_HOLD_DAYS})}
 if(req.method==='POST'&&url.pathname==='/api/partner/payout'){const db=load(),partner=partnerByToken(db,bearer(req));if(!partner)return json(res,401,{ok:false,message:'Acesso de parceiro inválido.'});const result=savePartnerPayout(db,partner,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/partner/withdrawals'){if(!rate(req,'withdrawal',4,86400000))return json(res,429,{ok:false,message:'Limite diário de solicitações atingido.'});const db=load(),partner=partnerByToken(db,bearer(req));if(!partner)return json(res,401,{ok:false,message:'Acesso de parceiro inválido.'});const result=requestWithdrawal(db,partner,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/register'){if(!rate(req,'web-register',8,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const db=load(),result=createAccount(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/login'){if(!rate(req,'web-login',12,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const db=load(),result=webLogin(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='GET'&&url.pathname==='/api/web/profile'){const db=load(),result=webProfile(db,bearer(req));return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/payment'){if(!rate(req,'payment',8,600000))return json(res,429,{ok:false,message:'Muitas tentativas de pagamento.'});const db=load(),auth=webProfile(db,bearer(req));if(auth.status!==200)return json(res,auth.status,auth.data);const input=await body(req),plan=String(input.plan||''),partner=db.partners.find(x=>x.slug===cookies(req).ice_ref&&x.status==='active'),result=await createMercadoPagoPayment(auth.user,plan,input,partner);if(result.paymentRaw){applyMercadoPagoPayment(db,result.paymentRaw);save(db)}return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/web/simulate-purchase'){if(process.env.NODE_ENV==='production')return json(res,410,{ok:false,message:'A compra simulada foi desativada. Finalize o pagamento pelo Mercado Pago.'});const b=await body(req),db=load(),result=simulatePurchase(db,bearer(req),String(b.plan||''));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/login'){const db=load(),result=loginAccount(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/profile'){const db=load(),result=profileByToken(db,bearer(req),await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
 if(req.method==='POST'&&url.pathname==='/api/account/register')return json(res,410,{ok:false,message:'Crie sua conta pelo site do Ice Optimizer.'});
 if(req.method==='POST'&&url.pathname==='/api/admin/login'){if(!rate(req,'admin-login',6,300000))return json(res,429,{ok:false,message:'Muitas tentativas.'});const b=await body(req);if(!ADMIN_PASSWORD||!safe(sha(b.password||''),sha(ADMIN_PASSWORD)))return json(res,401,{ok:false,message:'Senha incorreta.'});const exp=String(Date.now()+8*3600000),cookie=exp+'.'+hmac(exp);return json(res,200,{ok:true,csrf:hmac(cookie+'csrf').slice(0,32)},{'set-cookie':`ice_admin=${cookie}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}
 if(url.pathname.startsWith('/api/admin/')){if(!session(req))return json(res,401,{ok:false,message:'Sessão expirada.'});if(req.method!=='GET'&&!csrf(req))return json(res,403,{ok:false,message:'Atualize a página.'});const db=load();
  if(req.method==='GET'&&url.pathname==='/api/admin/customers')return json(res,200,{ok:true,csrf:hmac((cookies(req).ice_admin||'')+'csrf').slice(0,32),customers:db.users.map(u=>publicCustomer(u,db)),events:db.events.slice(0,80)});
  if(req.method==='GET'&&url.pathname==='/api/admin/partners')return json(res,200,{ok:true,csrf:hmac((cookies(req).ice_admin||'')+'csrf').slice(0,32),partners:db.partners.map(p=>partnerView(p,db)),orders:db.orders.slice(0,100),withdrawals:db.withdrawals,mercadoPagoReady:!!(MP_ACCESS_TOKEN&&MP_PUBLIC_KEY&&MP_WEBHOOK_SECRET&&PUBLIC_URL)});
  if(req.method==='POST'&&url.pathname==='/api/admin/partners'){const result=createPartner(db,await body(req));if(result.data.ok)save(db);return json(res,result.status,result.data)}
  const pm=url.pathname.match(/^\/api\/admin\/partners\/([0-9a-f-]+)\/status$/);if(req.method==='POST'&&pm){const partner=db.partners.find(x=>x.id===pm[1]);if(!partner)return json(res,404,{ok:false,message:'Parceiro não encontrado.'});const b=await body(req);partner.status=b.active?'active':'suspended';partner.updatedAt=new Date().toISOString();save(db);return json(res,200,{ok:true})}
  const wm=url.pathname.match(/^\/api\/admin\/withdrawals\/([0-9a-f-]+)\/status$/);if(req.method==='POST'&&wm){const withdrawal=db.withdrawals.find(x=>x.id===wm[1]);if(!withdrawal)return json(res,404,{ok:false,message:'Saque não encontrado.'});const b=await body(req),next=String(b.status||'');if(!['approved','paid','rejected'].includes(next))return json(res,400,{ok:false,message:'Status inválido.'});if(withdrawal.status==='paid')return json(res,409,{ok:false,message:'Este saque já foi pago.'});withdrawal.status=next;withdrawal.updatedAt=new Date().toISOString();withdrawal.note=String(b.note||'').slice(0,300);db.events.unshift({at:withdrawal.updatedAt,type:'withdrawal_'+next,partner:withdrawal.partnerId,withdrawal:withdrawal.id,amount:withdrawal.amount});save(db);return json(res,200,{ok:true})}
  const m=url.pathname.match(/^\/api\/admin\/customers\/([0-9a-f-]+)\/(status|reset-hwid)$/);if(req.method==='POST'&&m){const user=db.users.find(x=>x.id===m[1]),l=licenseFor(db,user);if(!user||!l)return json(res,404,{ok:false,message:'Cliente ou ativação não encontrado.'});const b=await body(req);if(m[2]==='status')l.revoked=!b.active;else{delete l.hardwareHash;delete l.deviceHash;delete l.hardwareBoundAt}db.events.unshift({at:new Date().toISOString(),type:m[2],user:user.id});save(db);return json(res,200,{ok:true})}
 }
 if(staticFile(req,res,url))return;json(res,404,{ok:false,message:'Não encontrado.'});
 }catch(e){console.error(e);if(!res.headersSent)json(res,500,{ok:false,message:'Erro interno.'});else res.end()}});
server.listen(PORT,()=>console.log('ice optimizer portal on '+PORT));
module.exports={server,load,save,duration,createAccount,webLogin,webProfile,simulatePurchase,loginAccount,profileByToken,hardwareAllowed,publicCustomer,createPartner,partnerByToken,partnerView,savePartnerPayout,requestWithdrawal,mpSignatureValid,paymentPayload,applyMercadoPagoPayment};
