using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Media;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

sealed class IcePageCanvas : Panel {
 readonly Catalog catalog;readonly string page;readonly Action<string> navigate;readonly Action<ActionItem[]> execute;readonly List<ActionItem> items;readonly HashSet<string> selected=new HashSet<string>();readonly TextBox search=new TextBox();
 int offset,hoverCard=-1,mouseX,mouseY;bool onlySelected;readonly bool[] settings={true,true,true,false,true,false};string hoverNav="";
 static readonly Color Bg=Color.FromArgb(3,14,26),Panel=Color.FromArgb(7,27,46),Panel2=Color.FromArgb(8,32,54),Line=Color.FromArgb(24,87,125),Cyan=Color.FromArgb(52,213,255),White=Color.FromArgb(232,246,255),Muted=Color.FromArgb(143,184,211),Green=Color.FromArgb(52,225,184);
 static readonly string[] NavKeys={"home","Windows","Jogos","Hardware","Reparos","Aplicativos","Ativações","Recuperação"};
 static readonly string[] NavLabels={"Início","Windows","Jogos","Hardware","Reparos","Aplicativos","Ativações","Recuperação"};
 static readonly int[] NavY={84,130,176,222,268,314,360,406};
 [DllImport("user32.dll",CharSet=CharSet.Unicode,EntryPoint="SendMessageW")]static extern IntPtr Cue(IntPtr h,int msg,IntPtr w,string text);
 bool IsActionPage{get{return page!="Início"&&page!="Minha conta"&&page!="Hardware"&&page!="Configurações";}}
 public IcePageCanvas(Catalog source,string name,Action<string> go,Action<ActionItem[]> run){catalog=source;page=name;navigate=go;execute=run;items=IsActionPage?catalog.actions.Where(a=>a.category==page).ToList():new List<ActionItem>();DoubleBuffered=true;SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);BackColor=Bg;TabStop=true;
  if(IsActionPage){search.BorderStyle=BorderStyle.None;search.BackColor=Color.FromArgb(5,25,43);search.ForeColor=White;search.Font=new Font("Segoe UI",9);search.SetBounds(739,153,190,22);search.HandleCreated+=(s,e)=>Cue(search.Handle,0x1501,(IntPtr)1,"Buscar ações...   Ctrl+F");search.TextChanged+=(s,e)=>{offset=0;Invalidate();};Controls.Add(search);}
  MouseEnter+=(s,e)=>Focus();
  MouseWheel+=(s,e)=>{if(!IsActionPage)return;int total=Filtered().Count;if(e.Delta<0&&offset+6<total)offset+=6;if(e.Delta>0&&offset>0)offset=Math.Max(0,offset-6);Invalidate();};
 }
 List<ActionItem> Filtered(){string q=search.Text.Trim();IEnumerable<ActionItem> result=string.IsNullOrEmpty(q)?items:items.Where(a=>(a.title+" "+a.description).IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0);if(onlySelected)result=result.Where(a=>selected.Contains(a.id));return result.ToList();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;g.Clear(Bg);DrawChrome(g);if(page=="Início")DrawHome(g);else if(page=="Minha conta")DrawAccount(g);else if(page=="Hardware")DrawHardware(g);else if(page=="Configurações")DrawSettings(g);else DrawActions(g);IceEffects.DrawSnow(g,Width,Height);}
 void DrawChrome(Graphics g){
  using(var p=new Pen(Color.FromArgb(110,55,211,255),2))g.DrawRoundedRectangle(p,new Rectangle(1,1,Width-3,Height-3),13);
  using(var b=new LinearGradientBrush(new Rectangle(0,0,194,Height),Color.FromArgb(5,25,43),Color.FromArgb(2,14,27),LinearGradientMode.Horizontal))g.FillRectangle(b,0,0,194,Height);
  using(var p=new Pen(Color.FromArgb(23,70,105)))g.DrawLine(p,194,0,194,Height);
  DrawDiamond(g,new Rectangle(23,18,26,42));DrawText(g,"ICE OPTIMIZER",new Rectangle(59,22,130,28),11,true,Cyan);
  for(int i=0;i<NavKeys.Length;i++)DrawNav(g,NavKeys[i],NavLabels[i],NavY[i],CountFor(NavKeys[i]),page==NavKeys[i]||(NavKeys[i]=="home"&&page=="Início"));
  using(var p=new Pen(Color.FromArgb(22,72,105)))g.DrawLine(p,16,495,178,495);
  DrawNav(g,"account","Minha conta",507,-1,page=="Minha conta");DrawNav(g,"Configurações","Configurações",553,-1,page=="Configurações");
  Round(g,new Rectangle(10,612,172,77),10,Color.FromArgb(7,35,60),Color.FromArgb(25,104,153));DrawText(g,"✦",new Rectangle(22,629,27,30),20,true,Cyan);DrawText(g,"ICE OPTIMIZER",new Rectangle(57,626,112,20),9,true,Cyan);DrawText(g,"v2.6.0",new Rectangle(57,645,80,16),8,false,Muted);DrawText(g,"Seu sistema no próximo nível.",new Rectangle(57,661,110,14),6.5f,false,Muted);
  DrawText(g,"ICE OPTIMIZER   /   "+page.ToUpperInvariant(),new Rectangle(221,24,460,22),7.5f,true,Cyan);DrawWindowButtons(g);
 }
 int CountFor(string key){if(key=="home")return-1;return catalog.actions.Count(a=>a.category==key);}
 void DrawNav(Graphics g,string key,string label,int y,int count,bool active){var r=new Rectangle(10,y,174,40);bool hover=hoverNav==key;if(active||hover){using(var b=new LinearGradientBrush(r,Color.FromArgb(active?21:12,174,245),Color.FromArgb(active?12:8,85,238),LinearGradientMode.Horizontal))Round(g,r,9,b,Color.FromArgb(active?150:70,70,220,255),active?2:1);}else Round(g,r,9,Color.FromArgb(6,25,43),Color.FromArgb(15,57,84));
  string icon=key=="home"?"⌂":key=="account"?"♙":key=="Configurações"?"⚙":key=="Jogos"?"◇":key=="Hardware"?"▣":key=="Reparos"?"⌕":key=="Recuperação"?"⬡":"▦";DrawText(g,icon,new Rectangle(22,y+7,27,26),14,true,active?White:Color.FromArgb(184,225,247));DrawText(g,label,new Rectangle(59,y+9,91,22),9,false,White);if(count>=0){Round(g,new Rectangle(145,y+7,28,26),9,Color.FromArgb(10,44,76),Color.Transparent);DrawText(g,count.ToString(),new Rectangle(145,y+8,28,24),8,false,White,ContentAlignment.MiddleCenter);}}
 void DrawWindowButtons(Graphics g){DrawText(g,"—",new Rectangle(1026,9,42,28),13,false,Muted,ContentAlignment.MiddleCenter);DrawText(g,"□",new Rectangle(1070,8,42,28),11,false,White,ContentAlignment.MiddleCenter);DrawText(g,"×",new Rectangle(1113,7,50,30),16,false,White,ContentAlignment.MiddleCenter);}
 void DrawActions(Graphics g){
  string title=page=="Ativações"?"Ativações do Windows":page;string subtitle=page=="Jogos"?"Mais FPS, menos latência e máxima estabilidade.":page=="Reparos"?"Corrija problemas e restaure funções do sistema.":page=="Aplicativos"?"Gerencie e remova aplicativos desnecessários.":page=="Recuperação"?"Proteja seu sistema antes de aplicar alterações.":page=="Ativações"?"Reative recursos e serviços quando precisar.":"Otimize o sistema com ajustes claros e organizados.";
  DrawText(g,title,new Rectangle(222,67,520,43),25,true,White);DrawText(g,subtitle,new Rectangle(223,107,590,25),9.5f,false,Muted);
  Round(g,new Rectangle(693,143,254,42),10,Color.FromArgb(5,25,43),Color.FromArgb(55,151,202));DrawText(g,"⌕",new Rectangle(708,150,28,27),14,false,Cyan);
  var filtered=Filtered();DrawText(g,filtered.Count+" ações disponíveis",new Rectangle(223,132,190,18),7.5f,false,Muted);
  Button(g,new Rectangle(222,163,144,36),"✓   Marcar página",selected.Count>0);Button(g,new Rectangle(374,163,139,36),"Limpar seleção",false);Button(g,new Rectangle(521,163,130,36),"Só selecionadas",onlySelected);
  int shown=Math.Min(6,Math.Max(0,filtered.Count-offset));for(int i=0;i<shown;i++){int col=i%2,row=i/2;DrawActionCard(g,filtered[offset+i],i,new Rectangle(222+col*326,213+row*137,314,125));}
  DrawPlan(g,filtered.Count);DrawText(g,filtered.Count==0?"Nenhuma ação encontrada.":"Role o mouse para ver as próximas ações.",new Rectangle(225,632,560,22),8,false,Muted);Button(g,new Rectangle(889,641,247,45),selected.Count==0?"▷   Selecione uma ação":"▷   Revisar e executar   →",selected.Count>0);
 }
 void DrawActionCard(Graphics g,ActionItem item,int index,Rectangle r){bool check=selected.Contains(item.id),hover=hoverCard==index;Round(g,r,12,hover?Color.FromArgb(12,48,77):Panel,hover?Color.FromArgb(80,195,234):Line,hover?2:1);if(hover){var path=new GraphicsPath();path.AddEllipse(mouseX-90,mouseY-90,180,180);using(var glow=new PathGradientBrush(path)){glow.CenterColor=Color.FromArgb(25,55,210,255);glow.SurroundColors=new[]{Color.Transparent};g.FillPath(glow,path);}}
  Round(g,new Rectangle(r.X+15,r.Y+14,38,38),10,Color.FromArgb(9,53,83),Color.FromArgb(25,107,151));DrawText(g,page=="Jogos"?"◇":page=="Reparos"?"⌕":page=="Recuperação"?"⬡":"▦",new Rectangle(r.X+19,r.Y+18,30,30),15,true,Cyan,ContentAlignment.MiddleCenter);
  Rectangle cb=new Rectangle(r.Right-34,r.Y+15,18,18);Round(g,cb,5,check?Cyan:Color.FromArgb(4,18,31),check?Cyan:Color.FromArgb(91,145,177));if(check)DrawText(g,"✓",cb,10,true,Color.FromArgb(2,26,41),ContentAlignment.MiddleCenter);
  DrawText(g,page.ToUpperInvariant(),new Rectangle(r.X+64,r.Y+13,150,16),6.5f,true,Muted);DrawText(g,item.risk=="high"?"AVANÇADO":"AJUSTE",new Rectangle(r.X+64,r.Y+28,130,15),6.5f,true,item.risk=="high"?Color.FromArgb(255,190,75):Green);
  DrawText(g,item.title,new Rectangle(r.X+15,r.Y+58,r.Width-30,22),10,true,White);DrawParagraph(g,item.description,new Rectangle(r.X+15,r.Y+82,r.Width-30,33),7.3f,Muted);
 }
 void DrawPlan(Graphics g,int total){var r=new Rectangle(875,213,274,409);Round(g,r,13,Panel,Line);DrawText(g,"SEU PLANO",new Rectangle(893,230,120,18),7,true,Cyan);DrawText(g,selected.Count.ToString("00"),new Rectangle(893,253,120,62),36,true,Cyan);DrawText(g,"ações selecionadas",new Rectangle(895,309,170,22),10,false,White);DrawText(g,selected.Count(a=>items.Any(x=>x.id==a&&x.risk=="high"))+" de alto impacto  ·  "+selected.Count(a=>items.Any(x=>x.id==a&&x.restart))+" pedem reinício",new Rectangle(895,337,230,20),7,false,Muted);using(var p=new Pen(Line))g.DrawLine(p,894,372,1129,372);DrawText(g,"⚡",new Rectangle(895,392,36,40),20,true,Cyan);DrawText(g,selected.Count==0?"Marque os cartões para montar\nsua fila de execução.":"Sua seleção está pronta.\nRevise antes de executar.",new Rectangle(936,391,188,49),9,false,Muted);DrawText(g,"⬡   Seguro e reversível",new Rectangle(896,477,210,22),8,false,Muted);DrawText(g,"▥   Exibe o impacto de cada ajuste",new Rectangle(896,509,225,22),8,false,Muted);DrawText(g,"◷   Você revisa antes de executar",new Rectangle(896,541,225,22),8,false,Muted);}
 void DrawHome(Graphics g){
  var state=LicenseGate.Current;string user=state==null||string.IsNullOrWhiteSpace(state.username)?"usuário":state.username;
  Round(g,new Rectangle(212,60,924,190),14,Color.FromArgb(5,26,45),Line);DrawText(g,"PAINEL GLACIAL",new Rectangle(236,77,180,20),8,true,Cyan);DrawText(g,"Bem-vindo de volta, "+user,new Rectangle(236,101,610,43),25,true,White);DrawText(g,"Seu sistema em alto desempenho, todos os dias.",new Rectangle(237,143,560,25),10,false,Muted);
  Round(g,new Rectangle(882,78,230,72),12,Color.FromArgb(6,31,51),Line);DrawText(g,"“  Mais desempenho",new Rectangle(900,88,190,22),9,false,Muted);DrawText(g,"    para o que realmente importa.  ”",new Rectangle(900,112,200,22),8,false,Muted);
  string[] statusTitles={"Sistema protegido","Atualizações em dia","Otimização pronta","Desempenho estável"};string[] statusSubs={"HWID ativo","Tudo atualizado","Seu PC mais rápido","Funcionando normalmente"};string[] statusIcons={"⬡","↻","◇","▥"};
  for(int i=0;i<4;i++){var r=new Rectangle(224+i*222,181,210,55);Round(g,r,10,Color.FromArgb(7,31,51),Color.FromArgb(23,101,137));DrawText(g,statusIcons[i],new Rectangle(r.X+13,r.Y+10,34,34),17,true,i==3?Green:Cyan,ContentAlignment.MiddleCenter);DrawText(g,statusTitles[i],new Rectangle(r.X+54,r.Y+8,145,20),8.2f,true,White);DrawText(g,statusSubs[i],new Rectangle(r.X+54,r.Y+28,145,18),7.2f,false,Muted);}
  string[] names={"Windows","Jogos","Hardware","Reparos","Aplicativos","Recuperação"};string[] desc={"Otimize o sistema, limpe o cache e melhore o desempenho.","Aumente o FPS, reduza travamentos e melhore a resposta.","Monitore os componentes e a estabilidade do PC.","Resolva problemas e mantenha o Windows saudável.","Gerencie e remova programas desnecessários.","Proteja o sistema com backup e restauração."};string[] icons={"▦","◇","▣","⌕","▦","⬡"};
  for(int i=0;i<6;i++){int col=i%3,row=i/3;var r=new Rectangle(212+col*222,265+row*180,210,166);Round(g,r,12,Panel,Line);DrawText(g,icons[i],new Rectangle(r.X+17,r.Y+16,39,39),20,true,Cyan,ContentAlignment.MiddleCenter);DrawText(g,names[i],new Rectangle(r.X+63,r.Y+19,105,24),11,true,White);Round(g,new Rectangle(r.Right-46,r.Y+16,31,29),10,Color.FromArgb(10,49,82),Color.Transparent);DrawText(g,CountFor(names[i]).ToString(),new Rectangle(r.Right-46,r.Y+18,31,25),8,true,White,ContentAlignment.MiddleCenter);DrawParagraph(g,desc[i],new Rectangle(r.X+17,r.Y+61,r.Width-34,55),8,Muted);Button(g,new Rectangle(r.X+17,r.Bottom-42,r.Width-34,30),"Gerenciar   →",false);}
  var sr=new Rectangle(890,265,246,346);Round(g,sr,12,Panel,Line);DrawText(g,"STATUS DO SISTEMA",new Rectangle(908,281,185,20),8,true,Cyan);using(var p=new Pen(Color.FromArgb(62,219,255),8))g.DrawArc(p,960,311,102,102,-80,300);DrawText(g,"✓",new Rectangle(977,330,68,68),27,true,Green,ContentAlignment.MiddleCenter);DrawText(g,"Sistema em ótimo estado",new Rectangle(910,417,206,26),11,true,White,ContentAlignment.MiddleCenter);DrawText(g,"Tudo funcionando como deveria.",new Rectangle(910,442,206,20),8,false,Muted,ContentAlignment.MiddleCenter);string[] checks={"Windows otimizado","Drivers verificados","Sistema protegido (HWID)","Espaço em disco otimizado"};for(int i=0;i<4;i++){DrawText(g,"●",new Rectangle(910,462+i*27,20,20),9,true,Green);DrawText(g,checks[i],new Rectangle(936,461+i*27,178,22),8,false,Muted);}Button(g,new Rectangle(908,574,210,42),"▷   Iniciar otimização   →",true);
  Round(g,new Rectangle(212,635,924,48),10,Color.FromArgb(6,25,43),Line);DrawText(g,"❄",new Rectangle(230,645,34,28),15,true,Cyan,ContentAlignment.MiddleCenter);DrawText(g,"“ Um sistema mais leve hoje, um amanhã com mais possibilidades. ”",new Rectangle(270,645,580,26),8.5f,false,Muted);
 }
 void DrawAccount(Graphics g){
  var state=LicenseGate.Current;string user=state==null||string.IsNullOrWhiteSpace(state.username)?"usuário":state.username,plan=state==null?"30 dias":LicenseGate.PlanName(state.plan),remaining=state==null?"30 dias restantes":LicenseGate.Remaining(state);DateTime parsed;string expiry=state!=null&&DateTime.TryParse(state.expiresAt,out parsed)?parsed.ToLocalTime().ToString("dd/MM/yyyy HH:mm"):"Permanente";string seen=state!=null&&DateTime.TryParse(state.lastValidated,out parsed)?parsed.ToLocalTime().ToString("dd/MM/yyyy HH:mm"):"Agora";
  DrawText(g,"♙",new Rectangle(222,65,48,48),25,true,Cyan,ContentAlignment.MiddleCenter);DrawText(g,"Minha conta",new Rectangle(278,67,430,42),25,true,White);DrawText(g,"Gerencie sua licença, segurança e acesso.",new Rectangle(279,107,500,22),9,false,Muted);
  Round(g,new Rectangle(212,146,535,466),13,Panel,Line);Round(g,new Rectangle(232,168,61,61),30,Color.FromArgb(10,67,106),Color.FromArgb(41,137,193));DrawText(g,"❄",new Rectangle(238,174,49,49),25,true,White,ContentAlignment.MiddleCenter);DrawText(g,user,new Rectangle(309,174,250,27),13,true,White);DrawText(g,"Plano "+plan,new Rectangle(309,201,220,20),8,false,Muted);Round(g,new Rectangle(642,177,78,30),10,Color.FromArgb(9,68,67),Color.Transparent);DrawText(g,"●  Ativa",new Rectangle(642,178,78,28),8,true,Green,ContentAlignment.MiddleCenter);
  DrawText(g,remaining,new Rectangle(232,249,260,25),10,true,Cyan);using(var b=new SolidBrush(Color.FromArgb(9,48,76)))g.FillRectangle(b,232,282,486,8);using(var b=new SolidBrush(Color.FromArgb(47,177,244)))g.FillRectangle(b,232,282,394,8);DrawText(g,"Válida até "+expiry,new Rectangle(232,299,330,21),8,false,Muted);
  string[] ok={"Conta validada neste computador","Uso offline disponível por até 72 horas","HWID protegido","Todas as funcionalidades liberadas"};for(int i=0;i<4;i++){DrawText(g,"●",new Rectangle(232,340+i*34,22,20),9,true,Green);DrawText(g,ok[i],new Rectangle(260,338+i*34,360,24),8.5f,false,Muted);}
  Button(g,new Rectangle(232,502,238,45),"◉   Alterar senha",false);Button(g,new Rectangle(482,502,238,45),"↪   Sair da conta",false);
  Round(g,new Rectangle(763,146,373,274),13,Panel,Line);DrawText(g,"Informações da conta",new Rectangle(783,164,300,27),11,true,White);string[] labels={"Usuário","Plano","Status","Válido até","HWID","Último acesso"};string[] values={user,plan,"Ativa",expiry,"Protegido",seen};for(int i=0;i<6;i++){int y=205+i*33;DrawText(g,labels[i],new Rectangle(784,y,115,23),8,false,Muted);DrawText(g,values[i],new Rectangle(908,y,198,23),8,false,i==2?Green:White);using(var p=new Pen(Color.FromArgb(13,55,80)))g.DrawLine(p,784,y+28,1111,y+28);}
  Round(g,new Rectangle(763,436,373,176),13,Panel,Line);DrawText(g,"Gerenciar licença",new Rectangle(783,455,300,25),11,true,White);DrawText(g,"Precisa de um novo plano ou quer renovar seu acesso?",new Rectangle(783,489,325,24),8,false,Muted);DrawText(g,"Acesse nossa loja ou entre em contato.",new Rectangle(783,514,300,22),8,false,Muted);Button(g,new Rectangle(783,551,333,44),"Gerenciar / Renovar plano   →",true);
 }
 void DrawHardware(Graphics g){
  DrawText(g,"Hardware",new Rectangle(222,68,500,42),25,true,White);DrawText(g,"Monitore os componentes e mantenha seu computador em boas condições.",new Rectangle(223,108,600,24),9.5f,false,Muted);Round(g,new Rectangle(871,66,264,54),10,Color.FromArgb(6,34,49),Color.FromArgb(24,91,119));DrawText(g,"●",new Rectangle(888,81,23,23),13,true,Green);DrawText(g,"Sistema pronto",new Rectangle(916,77,180,20),10,true,Green);DrawText(g,"Hardware detectado corretamente",new Rectangle(916,97,200,16),7,false,Muted);
  string cpu=Environment.GetEnvironmentVariable("PROCESSOR_IDENTIFIER")??"Processador detectado";if(cpu.Length>30)cpu=cpu.Substring(0,30);DriveInfo drive=DriveInfo.GetDrives().FirstOrDefault(d=>d.IsReady&&d.Name.StartsWith("C"));string disk=drive==null?"Disco do sistema":Math.Round((drive.TotalSize-drive.AvailableFreeSpace)/1073741824d)+" / "+Math.Round(drive.TotalSize/1073741824d)+" GB";
  HardwareCard(g,new Rectangle(212,151,216,174),"CPU",cpu,"Ativo",Cyan);HardwareCard(g,new Rectangle(440,151,216,174),"GPU","Adaptador gráfico do sistema","Detectada",Green);HardwareCard(g,new Rectangle(668,151,216,174),"RAM",Environment.Is64BitOperatingSystem?"Sistema de 64 bits":"Sistema de 32 bits","Em uso",Color.FromArgb(154,105,255));HardwareCard(g,new Rectangle(896,151,240,174),"Armazenamento",disk,"Saudável",Cyan);
  InfoPanel(g,new Rectangle(212,339,290,244),"Temperatura",new[]{"CPU        Monitorando","GPU        Monitorando","Placa-mãe  Disponível","SSD        Saudável"});InfoPanel(g,new Rectangle(514,339,290,244),"Saúde dos dispositivos",new[]{"✓ CPU funcionando normalmente","✓ Memória sem erros detectados","✓ Armazenamento em bom estado","✓ Drivers disponíveis"});InfoPanel(g,new Rectangle(816,339,320,244),"Resumo do sistema",new[]{"Seu hardware está em boas condições!","Tudo funciona dentro do esperado.","Mantenha os drivers atualizados.","Faça verificações periódicas."});Round(g,new Rectangle(212,600,924,70),10,Panel,Line);DrawText(g,"◴",new Rectangle(231,615,42,40),22,true,Cyan);DrawText(g,"Desempenho geral do hardware",new Rectangle(283,611,350,24),10,true,White);DrawText(g,"Componentes reconhecidos e prontos para uso.",new Rectangle(283,637,430,20),8,false,Muted);DrawText(g,"EXCELENTE",new Rectangle(1013,620,100,25),8,true,Green,ContentAlignment.MiddleCenter);
 }
 void HardwareCard(Graphics g,Rectangle r,string title,string detail,string state,Color accent){Round(g,r,11,Panel,Line);DrawText(g,"▣",new Rectangle(r.X+16,r.Y+18,35,35),18,true,accent);DrawText(g,title,new Rectangle(r.X+58,r.Y+18,r.Width-72,22),10,true,White);DrawText(g,detail,new Rectangle(r.X+17,r.Y+60,r.Width-34,37),7.5f,false,Muted);DrawText(g,state,new Rectangle(r.X+17,r.Y+112,r.Width-34,30),16,true,White);using(var b=new SolidBrush(Color.FromArgb(8,47,74)))g.FillRectangle(b,r.X+17,r.Bottom-23,r.Width-34,6);using(var b=new SolidBrush(accent))g.FillRectangle(b,r.X+17,r.Bottom-23,(r.Width-34)*2/3,6);}
 void InfoPanel(Graphics g,Rectangle r,string title,string[] lines){Round(g,r,11,Panel,Line);DrawText(g,title,new Rectangle(r.X+17,r.Y+15,r.Width-34,24),10,true,White);int y=r.Y+57;foreach(var line in lines){DrawText(g,line,new Rectangle(r.X+17,y,r.Width-34,25),8,false,line.StartsWith("✓")?Green:Muted);y+=39;}}
 void DrawSettings(Graphics g){
  DrawText(g,"Configurações",new Rectangle(222,68,500,42),25,true,White);DrawText(g,"Personalize a experiência do Ice Optimizer.",new Rectangle(223,108,600,24),9.5f,false,Muted);
  Setting(g,new Rectangle(222,158,444,92),"Efeitos sonoros","Reproduzir sons discretos ao clicar e selecionar.",settings[0]);Setting(g,new Rectangle(680,158,456,92),"Animações fluidas","Usar transições e iluminação na interface.",settings[1]);Setting(g,new Rectangle(222,264,444,92),"Confirmar ações","Revisar o plano antes de qualquer execução.",settings[2]);Setting(g,new Rectangle(680,264,456,92),"Iniciar com o Windows","Abrir o Ice Optimizer ao entrar no sistema.",settings[3]);Setting(g,new Rectangle(222,370,444,92),"Atualizações automáticas","Verificar novas versões do aplicativo.",settings[4]);Setting(g,new Rectangle(680,370,456,92),"Modo econômico","Reduzir efeitos quando a janela estiver inativa.",settings[5]);
  Round(g,new Rectangle(222,487,914,132),12,Panel,Line);DrawText(g,"Sobre o Ice Optimizer",new Rectangle(244,506,310,25),11,true,White);DrawText(g,"Edição Glacial  ·  v2.6.0",new Rectangle(244,541,500,23),9,false,Muted);DrawText(g,"Ajustes organizados, proteção por HWID e controle total sobre cada alteração.",new Rectangle(244,574,680,22),8,false,Muted);Button(g,new Rectangle(902,534,210,45),"Verificar atualizações",true);
 }
 void Setting(Graphics g,Rectangle r,string title,string description,bool enabled){Round(g,r,11,Panel,Line);DrawText(g,title,new Rectangle(r.X+18,r.Y+17,r.Width-100,24),10,true,White);DrawText(g,description,new Rectangle(r.X+18,r.Y+47,r.Width-100,25),8,false,Muted);Round(g,new Rectangle(r.Right-67,r.Y+27,45,24),12,enabled?Color.FromArgb(18,147,225):Color.FromArgb(8,37,58),enabled?Cyan:Line);using(var b=new SolidBrush(Color.White))g.FillEllipse(b,enabled?r.Right-45:r.Right-64,r.Y+30,18,18);}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);mouseX=e.X;mouseY=e.Y;string old=hoverNav;hoverNav="";for(int i=0;i<NavY.Length;i++)if(new Rectangle(10,NavY[i],174,40).Contains(e.Location))hoverNav=NavKeys[i];if(new Rectangle(10,507,174,40).Contains(e.Location))hoverNav="account";if(new Rectangle(10,553,174,40).Contains(e.Location))hoverNav="Configurações";int hc=-1;if(IsActionPage)for(int i=0;i<6;i++){int col=i%2,row=i/2;if(new Rectangle(222+col*326,213+row*137,314,125).Contains(e.Location))hc=i;}if(old!=hoverNav||hc!=hoverCard||hc>=0){hoverCard=hc;Invalidate();}Cursor=hoverNav!=""||hoverCard>=0?Cursors.Hand:Cursors.Default;}
 protected override void OnMouseLeave(EventArgs e){hoverNav="";hoverCard=-1;Invalidate();base.OnMouseLeave(e);}
 protected override void OnMouseClick(MouseEventArgs e){base.OnMouseClick(e);IceAudio.Click();if(new Rectangle(1026,5,43,34).Contains(e.Location)){var form=FindForm();if(form!=null)form.BeginInvoke(new Action(()=>form.WindowState=FormWindowState.Minimized));return;}if(new Rectangle(1113,5,50,34).Contains(e.Location)){FindForm().Close();return;}for(int i=0;i<NavY.Length;i++)if(new Rectangle(10,NavY[i],174,40).Contains(e.Location)){navigate(NavKeys[i]);return;}if(new Rectangle(10,507,174,40).Contains(e.Location)){navigate("account");return;}if(new Rectangle(10,553,174,40).Contains(e.Location)){navigate("Configurações");return;}if(page=="Início"){string[] targets={"Windows","Jogos","Hardware","Reparos","Aplicativos","Recuperação"};for(int i=0;i<6;i++){int col=i%3,row=i/3;if(new Rectangle(212+col*222,265+row*180,210,166).Contains(e.Location)){navigate(targets[i]);return;}}if(new Rectangle(908,574,210,42).Contains(e.Location)){navigate("Windows");return;}return;}if(page=="Minha conta"){if(new Rectangle(482,502,238,45).Contains(e.Location)){navigate("logout");return;}if(new Rectangle(232,502,238,45).Contains(e.Location)||new Rectangle(783,551,333,44).Contains(e.Location)){try{Process.Start(new ProcessStartInfo("https://iceotimizacoes.store/#planos"){UseShellExecute=true});}catch{}return;}return;}if(page=="Configurações"){Rectangle[] boxes={new Rectangle(222,158,444,92),new Rectangle(680,158,456,92),new Rectangle(222,264,444,92),new Rectangle(680,264,456,92),new Rectangle(222,370,444,92),new Rectangle(680,370,456,92)};for(int i=0;i<boxes.Length;i++)if(boxes[i].Contains(e.Location)){settings[i]=!settings[i];if(i==0)IceAudio.Enabled=settings[i];if(i==1)IceEffects.AnimationsEnabled=settings[i];Invalidate();return;}if(new Rectangle(902,534,210,45).Contains(e.Location)){try{Process.Start(new ProcessStartInfo("https://iceotimizacoes.store/"){UseShellExecute=true});}catch{}return;}return;}if(page=="Hardware")return;
  if(new Rectangle(222,163,144,36).Contains(e.Location)){foreach(var a in Filtered().Skip(offset).Take(6))selected.Add(a.id);Invalidate();return;}if(new Rectangle(374,163,139,36).Contains(e.Location)){selected.Clear();onlySelected=false;offset=0;Invalidate();return;}if(new Rectangle(521,163,130,36).Contains(e.Location)){onlySelected=!onlySelected;offset=0;Invalidate();return;}if(new Rectangle(889,641,247,45).Contains(e.Location)&&selected.Count>0){execute(items.Where(a=>selected.Contains(a.id)).ToArray());return;}
  var filtered=Filtered();for(int i=0;i<6&&offset+i<filtered.Count;i++){int col=i%2,row=i/2;if(new Rectangle(222+col*326,213+row*137,314,125).Contains(e.Location)){var a=filtered[offset+i];if(!selected.Add(a.id))selected.Remove(a.id);Invalidate();return;}}
 }
 void Button(Graphics g,Rectangle r,string label,bool active){Round(g,r,9,active?Color.FromArgb(10,70,102):Color.FromArgb(6,26,44),active?Color.FromArgb(58,202,242):Line);DrawText(g,label,r,8.5f,active,active?White:Muted,ContentAlignment.MiddleCenter);}
 void DrawDiamond(Graphics g,Rectangle r){Point[] a={new Point(r.X+r.Width/2,r.Y),new Point(r.Right,r.Y+r.Height/2),new Point(r.X+r.Width/2,r.Bottom),new Point(r.X,r.Y+r.Height/2)};using(var b=new LinearGradientBrush(r,Color.White,Color.FromArgb(21,171,245),LinearGradientMode.ForwardDiagonal))g.FillPolygon(b,a);using(var p=new Pen(Color.FromArgb(137,235,255)))g.DrawPolygon(p,a);}
 static void Round(Graphics g,Rectangle r,int radius,Color fill,Color stroke,int width=1){using(var path=Path(r,radius)){using(var b=new SolidBrush(fill))g.FillPath(b,path);if(stroke.A>0)using(var p=new Pen(stroke,width))g.DrawPath(p,path);}}
 static void Round(Graphics g,Rectangle r,int radius,Brush fill,Color stroke,int width=1){using(var path=Path(r,radius)){g.FillPath(fill,path);if(stroke.A>0)using(var p=new Pen(stroke,width))g.DrawPath(p,path);}}
 static GraphicsPath Path(Rectangle r,int d){var p=new GraphicsPath();p.AddArc(r.X,r.Y,d,d,180,90);p.AddArc(r.Right-d,r.Y,d,d,270,90);p.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);p.AddArc(r.X,r.Bottom-d,d,d,90,90);p.CloseFigure();return p;}
 static void DrawText(Graphics g,string value,Rectangle r,float size,bool bold,Color color,ContentAlignment align=ContentAlignment.MiddleLeft){using(var f=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular)){var flags=TextFormatFlags.EndEllipsis|TextFormatFlags.NoPadding;if(align==ContentAlignment.MiddleCenter)flags|=TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter;else flags|=TextFormatFlags.Left|TextFormatFlags.VerticalCenter;TextRenderer.DrawText(g,value,f,r,color,flags);}}
 static void DrawParagraph(Graphics g,string value,Rectangle r,float size,Color color){using(var f=new Font("Segoe UI",size)){TextRenderer.DrawText(g,value,f,r,color,TextFormatFlags.Left|TextFormatFlags.Top|TextFormatFlags.WordBreak|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPadding);}}
}

static class IceAudio {
 public static bool Enabled=true;static SoundPlayer player;
 public static void Click(){if(!Enabled)return;try{if(player==null){var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("ice-click.wav");if(stream==null)return;player=new SoundPlayer(stream);player.Load();}player.Play();}catch{}}
}

static class IceEffects {
 public static bool AnimationsEnabled=true;
 public static void DrawSnow(Graphics g,int width,int height){if(!AnimationsEnabled)return;long t=Environment.TickCount&0x7fffffff;for(int i=0;i<26;i++){float speed=.018f+(i%5)*.005f;float x=(float)((i*173+(t*speed*(1+(i%3)*.12)))%Math.Max(1,width));float y=(float)((i*89+(t*(.025f+(i%4)*.007f)))%Math.Max(1,height));int size=1+i%3;using(var b=new SolidBrush(Color.FromArgb(35+(i%4)*15,190,235,255)))g.FillEllipse(b,x,y,size,size);}}
}

sealed class IceProgressForm : Form {
 readonly Label title=new Label(),status=new Label(),notice=new Label();readonly Panel fill=new Panel(),track=new Panel();int value;
 public IceProgressForm(){Text="Ice Optimizer — execução";ClientSize=new Size(520,260);FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterParent;BackColor=Color.FromArgb(3,15,28);ShowInTaskbar=false;TopMost=true;
  Paint+=(s,e)=>{e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var p=new Pen(Color.FromArgb(68,218,255),2))e.Graphics.DrawRoundedRectangle(p,new Rectangle(1,1,Width-3,Height-3),14);using(var b=new LinearGradientBrush(new Rectangle(0,0,Width,95),Color.FromArgb(7,52,84),Color.FromArgb(3,15,28),LinearGradientMode.Vertical))e.Graphics.FillRectangle(b,2,2,Width-4,93);};
  title.Text="PREPARANDO SUA OTIMIZAÇÃO";title.Font=new Font("Segoe UI",14,FontStyle.Bold);title.ForeColor=Color.White;title.BackColor=Color.Transparent;title.TextAlign=ContentAlignment.MiddleCenter;title.SetBounds(25,32,470,34);Controls.Add(title);
  status.Text="Organizando os arquivos necessários...";status.Font=new Font("Segoe UI",9);status.ForeColor=Color.FromArgb(157,202,228);status.TextAlign=ContentAlignment.MiddleCenter;status.SetBounds(30,83,460,28);Controls.Add(status);
  track.BackColor=Color.FromArgb(8,43,68);track.SetBounds(42,130,436,14);Controls.Add(track);fill.BackColor=Color.FromArgb(48,211,255);fill.SetBounds(0,0,0,14);track.Controls.Add(fill);
  notice.Text="❄  Aguarde. O mouse fica bloqueado até a operação terminar.";notice.Font=new Font("Segoe UI",8.5f);notice.ForeColor=Color.FromArgb(103,213,244);notice.TextAlign=ContentAlignment.MiddleCenter;notice.SetBounds(28,170,464,45);Controls.Add(notice);
 }
 public void Report(string phase,int index,int total,ActionItem item){if(InvokeRequired){BeginInvoke(new Action<string,int,int,ActionItem>(Report),phase,index,total,item);return;}value=total<=0?0:(int)Math.Round(index*100d/total);title.Text=phase=="download"?"PREPARANDO ARQUIVOS":phase=="execute"?"APLICANDO AJUSTES":"FINALIZANDO";status.Text=item==null?"Concluindo...":item.title+"  ·  "+value+"%";fill.Width=Math.Max(2,(track.Width*value)/100);Refresh();}
 public void Complete(){if(InvokeRequired){BeginInvoke(new Action(Complete));return;}value=100;title.Text="OTIMIZAÇÃO CONCLUÍDA";status.Text="100%  ·  Todas as etapas foram finalizadas.";fill.Width=track.Width;Refresh();}
}

sealed class ExecutionResultsForm : Form {
 readonly Color bg=Color.FromArgb(3,15,28),panel=Color.FromArgb(7,29,49),line=Color.FromArgb(24,91,128),cyan=Color.FromArgb(54,215,255),white=Color.FromArgb(233,246,255),muted=Color.FromArgb(142,185,211),green=Color.FromArgb(53,225,184),red=Color.FromArgb(255,103,116);
 public ExecutionResultsForm(IList<BatchResult> results){
  Text="Ice Optimizer — relatório";ClientSize=new Size(760,610);MinimumSize=MaximumSize=Size;FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterParent;BackColor=bg;ShowInTaskbar=false;
  int success=results.Count(x=>x.code==0),failed=results.Count-success;
  Paint+=(s,e)=>{e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var p=new Pen(Color.FromArgb(77,220,255),2))e.Graphics.DrawRoundedRectangle(p,new Rectangle(1,1,Width-3,Height-3),14);using(var b=new LinearGradientBrush(new Rectangle(2,2,Width-4,123),Color.FromArgb(8,57,91),bg,LinearGradientMode.Vertical))e.Graphics.FillRectangle(b,2,2,Width-4,121);};
  var title=LabelOf("RELATÓRIO DA OTIMIZAÇÃO",new Rectangle(42,30,590,31),16,true,white);Controls.Add(title);var close=LabelOf("×",new Rectangle(700,18,40,34),18,false,muted);close.TextAlign=ContentAlignment.MiddleCenter;close.Cursor=Cursors.Hand;close.Click+=(s,e)=>Close();Controls.Add(close);
  var summary=LabelOf(success+" concluída(s) com sucesso"+(failed>0?"   ·   "+failed+" com erro":"   ·   Tudo certo"),new Rectangle(43,69,650,25),9,false,failed==0?green:Color.FromArgb(255,194,91));Controls.Add(summary);
  var list=new FlowLayoutPanel{Location=new Point(34,121),Size=new Size(692,403),AutoScroll=true,FlowDirection=FlowDirection.TopDown,WrapContents=false,BackColor=Color.Transparent,Padding=new Padding(0,0,8,0)};Controls.Add(list);
  foreach(var result in results){bool ok=result.code==0;var row=new Panel{Size=new Size(661,82),Margin=new Padding(0,0,0,10),BackColor=panel};row.Paint+=(s,e)=>{e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var p=new Pen(ok?Color.FromArgb(32,133,113):Color.FromArgb(133,55,68)))e.Graphics.DrawRoundedRectangle(p,new Rectangle(0,0,row.Width-1,row.Height-1),10);};var icon=LabelOf(ok?"✓":"×",new Rectangle(17,17,46,46),19,true,ok?green:red);icon.TextAlign=ContentAlignment.MiddleCenter;row.Controls.Add(icon);row.Controls.Add(LabelOf(result.title,new Rectangle(76,12,555,27),10.5f,true,white));string detail=ok?"Ação aplicada corretamente.":result.status;row.Controls.Add(LabelOf(detail,new Rectangle(76,41,555,29),8,false,ok?green:Color.FromArgb(255,170,176)));list.Controls.Add(row);}
  string log=SaveLog(results);var saved=LabelOf("Registro salvo em: "+log,new Rectangle(38,536,535,25),7.5f,false,muted);Controls.Add(saved);var done=new Button{Text="Concluir",FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(12,112,171),ForeColor=white,Font=new Font("Segoe UI",9,FontStyle.Bold),Cursor=Cursors.Hand};done.FlatAppearance.BorderColor=cyan;done.SetBounds(594,542,132,42);done.Click+=(s,e)=>Close();Controls.Add(done);
 }
 Label LabelOf(string text,Rectangle bounds,float size,bool bold,Color color){return new Label{Text=text,Bounds=bounds,Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular),ForeColor=color,BackColor=Color.Transparent,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=true};}
 string SaveLog(IList<BatchResult> results){try{string folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ice optimizer","logs");Directory.CreateDirectory(folder);string file=Path.Combine(folder,DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss")+".txt");var lines=new List<string>{"ICE OPTIMIZER — RELATÓRIO DE EXECUÇÃO","Data: "+DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"),new string('=',64)};foreach(var result in results)lines.Add((result.code==0?"[SUCESSO] ":"[ERRO] ")+result.title+" — "+result.status);File.WriteAllLines(file,lines);return file;}catch{return "não foi possível salvar o arquivo";}}
}

sealed class ScriptSyncForm : Form {
 readonly Label title=new Label(),status=new Label(),percent=new Label();readonly Panel track=new Panel(),fill=new Panel();
 ScriptSyncForm(){Text="Ice Optimizer — atualização";ClientSize=new Size(550,280);FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterScreen;BackColor=Color.FromArgb(3,15,28);ShowInTaskbar=false;TopMost=true;
  Paint+=(s,e)=>{e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var p=new Pen(Color.FromArgb(65,216,255),2))e.Graphics.DrawRoundedRectangle(p,new Rectangle(1,1,Width-3,Height-3),14);using(var b=new LinearGradientBrush(new Rectangle(2,2,Width-4,102),Color.FromArgb(8,58,91),Color.FromArgb(3,15,28),LinearGradientMode.Vertical))e.Graphics.FillRectangle(b,2,2,Width-4,100);};
  title.Text="SINCRONIZANDO AJUSTES";title.Font=new Font("Segoe UI",14,FontStyle.Bold);title.ForeColor=Color.White;title.BackColor=Color.Transparent;title.TextAlign=ContentAlignment.MiddleCenter;title.SetBounds(30,35,490,34);Controls.Add(title);
  status.Text="Conectando ao servidor seguro...";status.Font=new Font("Segoe UI",8.5f);status.ForeColor=Color.FromArgb(154,199,225);status.TextAlign=ContentAlignment.MiddleCenter;status.SetBounds(35,91,480,25);Controls.Add(status);
  track.BackColor=Color.FromArgb(7,42,67);track.SetBounds(46,139,458,15);Controls.Add(track);fill.BackColor=Color.FromArgb(49,212,255);fill.SetBounds(0,0,2,15);track.Controls.Add(fill);
  percent.Text="0%";percent.Font=new Font("Segoe UI",18,FontStyle.Bold);percent.ForeColor=Color.FromArgb(65,218,255);percent.TextAlign=ContentAlignment.MiddleCenter;percent.SetBounds(215,170,120,38);Controls.Add(percent);
  var note=new Label{Text="Uma cópia nova e verificada dos scripts é baixada sempre que o aplicativo abre.",Font=new Font("Segoe UI",7.5f),ForeColor=Color.FromArgb(103,179,213),TextAlign=ContentAlignment.MiddleCenter};note.SetBounds(35,219,480,32);Controls.Add(note);
 }
 void ReportFile(string file,int current,int total){if(InvokeRequired){BeginInvoke(new Action<string,int,int>(ReportFile),file,current,total);return;}int value=total<=0?0:(int)Math.Round(current*100d/total);status.Text="Verificando "+file+"  ·  "+current+" de "+total;percent.Text=value+"%";fill.Width=Math.Max(2,track.Width*value/100);Refresh();}
 public static bool Sync(Catalog catalog){using(var form=new ScriptSyncForm()){form.Show();Application.DoEvents();Exception failure=null;var task=Task.Run(async()=>{try{await Payload.RefreshOnline(catalog,LicenseGate.Current==null?null:LicenseGate.Current.token,form.ReportFile);}catch(Exception ex){failure=ex;}});while(!task.IsCompleted){Application.DoEvents();Thread.Sleep(15);}task.GetAwaiter().GetResult();if(failure!=null){form.Close();MessageBox.Show("Não foi possível baixar os scripts verificados.\n\n"+failure.Message,"Conexão necessária",MessageBoxButtons.OK,MessageBoxIcon.Error);return false;}form.ReportFile("Concluído",1,1);Application.DoEvents();Thread.Sleep(180);form.Close();return true;}}
}

static class GraphicsIceExtensions {
 public static void DrawRoundedRectangle(this Graphics g,Pen pen,Rectangle r,int radius){using(var p=new GraphicsPath()){p.AddArc(r.X,r.Y,radius,radius,180,90);p.AddArc(r.Right-radius,r.Y,radius,radius,270,90);p.AddArc(r.Right-radius,r.Bottom-radius,radius,radius,0,90);p.AddArc(r.X,r.Bottom-radius,radius,radius,90,90);p.CloseFigure();g.DrawPath(pen,p);}}
}


