using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;

public class LicenseState {public string token,username,plan,expiresAt,createdAt,lastValidated;}
public static class LicenseGate {
 static readonly string folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ice optimizer"),file=Path.Combine(folder,"account.dat");
 public static LicenseState Current{get;private set;}
 internal static string Device(){string machine="";try{using(var k=Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Cryptography"))machine=Convert.ToString(k.GetValue("MachineGuid"));}catch{}using(var h=SHA256.Create())return Convert.ToBase64String(h.ComputeHash(Encoding.UTF8.GetBytes(machine+"|"+Environment.MachineName)));}
 static LicenseState Read(){try{var enc=File.ReadAllBytes(file);var raw=ProtectedData.Unprotect(enc,null,DataProtectionScope.CurrentUser);return new JavaScriptSerializer().Deserialize<LicenseState>(Encoding.UTF8.GetString(raw));}catch{return null;}}
 static void Save(LicenseState state){Directory.CreateDirectory(folder);var raw=Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(state));File.WriteAllBytes(file,ProtectedData.Protect(raw,null,DataProtectionScope.CurrentUser));}
 static LicenseState StateFrom(Dictionary<string,object> data,LicenseState state=null){state=state??new LicenseState();if(data.ContainsKey("token")&&data["token"]!=null)state.token=Convert.ToString(data["token"]);if(data.ContainsKey("username"))state.username=Convert.ToString(data["username"]);if(data.ContainsKey("plan"))state.plan=Convert.ToString(data["plan"]);state.expiresAt=data.ContainsKey("expiresAt")?Convert.ToString(data["expiresAt"]):null;if(data.ContainsKey("createdAt"))state.createdAt=Convert.ToString(data["createdAt"]);state.lastValidated=DateTime.UtcNow.ToString("o");return state;}
 internal static async Task<Dictionary<string,object>> Request(Catalog catalog,string endpoint,Dictionary<string,string> fields,string token=null){using(var c=new HttpClient{Timeout=TimeSpan.FromSeconds(15)}){c.DefaultRequestHeaders.Add("User-Agent","ice-optimizer/2.2");if(!string.IsNullOrEmpty(token))c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);fields["deviceId"]=Device();var body=new JavaScriptSerializer().Serialize(fields);using(var response=await c.PostAsync(catalog.licenseApi+endpoint,new StringContent(body,Encoding.UTF8,"application/json"))){var text=await response.Content.ReadAsStringAsync();var data=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(text);if(!response.IsSuccessStatusCode)throw new InvalidOperationException(data!=null&&data.ContainsKey("message")?Convert.ToString(data["message"]):"Acesso recusado.");return data;}}}
 public static bool Ensure(Catalog catalog){var state=Read();if(state!=null&&!string.IsNullOrWhiteSpace(state.token)){try{var r=Request(catalog,"/api/account/profile",new Dictionary<string,string>(),state.token).GetAwaiter().GetResult();Current=StateFrom(r,state);Save(Current);return true;}catch(HttpRequestException){DateTime last;if(DateTime.TryParse(state.lastValidated,out last)&&DateTime.UtcNow-last.ToUniversalTime()<TimeSpan.FromHours(72)&&(string.IsNullOrEmpty(state.expiresAt)||DateTime.Parse(state.expiresAt).ToUniversalTime()>DateTime.UtcNow)){Current=state;return true;}}catch(TaskCanceledException){DateTime last;if(DateTime.TryParse(state.lastValidated,out last)&&DateTime.UtcNow-last.ToUniversalTime()<TimeSpan.FromHours(72)){Current=state;return true;}}catch{}}
  using(var form=new AccountForm(catalog,state==null?"":state.username)){if(form.ShowDialog()!=DialogResult.OK)return false;Current=form.State;Save(Current);return true;}}
 public static string PlanName(string plan){return plan=="d30"?"30 dias":plan=="d90"?"90 dias":plan=="m6"?"6 meses":plan=="permanent"?"Permanente":"Licença";}
 public static string Remaining(LicenseState s){if(s==null)return "Indisponível";if(string.IsNullOrEmpty(s.expiresAt))return "Acesso permanente";DateTime end;if(!DateTime.TryParse(s.expiresAt,out end))return "Indisponível";var left=end.ToUniversalTime()-DateTime.UtcNow;if(left<=TimeSpan.Zero)return "Expirada";if(left.TotalDays>=1)return Math.Ceiling(left.TotalDays)+" dias restantes";return Math.Max(1,Math.Ceiling(left.TotalHours))+" horas restantes";}
}
public class AccountForm:Form {
 readonly Catalog catalog;TextBox username=new TextBox(),password=new TextBox(),licenseKey=new TextBox();Label message=new Label(),keyCaption=new Label();IceButton submit=new IceButton(),loginMode=new IceButton(),registerMode=new IceButton();bool registering;public LicenseState State;
 public AccountForm(Catalog c,string previous){catalog=c;Text="Conta Ice Optimizer";Size=new Size(650,660);StartPosition=FormStartPosition.CenterScreen;BackColor=Ice.Bg;ForeColor=Ice.Text;Font=Ice.Font(10);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;using(var s=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("ice.ico"))if(s!=null)Icon=new Icon(s);
  var logo=new Panel{BackColor=Ice.Bg};logo.SetBounds(35,27,70,70);logo.Paint+=(s,e)=>Ice.Crystal(e.Graphics,new RectangleF(9,2,50,65),Motion.Phase);Controls.Add(logo);var title=MakeLabel("Sua conta glacial",23,Ice.Text,true);title.SetBounds(125,34,450,45);Controls.Add(title);var sub=MakeLabel("Entre para acessar o Ice Optimizer neste computador.",10,Ice.Muted);sub.SetBounds(128,79,450,30);Controls.Add(sub);
  loginMode.Text="Entrar";loginMode.Active=true;loginMode.SetBounds(38,127,270,42);registerMode.Text="Criar conta";registerMode.SetBounds(318,127,270,42);Controls.Add(loginMode);Controls.Add(registerMode);loginMode.Click+=(s,e)=>SetMode(false);registerMode.Click+=(s,e)=>SetMode(true);
  AddField("NOME DE USUÁRIO",username,38,197);username.Text=previous;AddField("SENHA",password,38,287);password.UseSystemPasswordChar=true;
  keyCaption=MakeLabel("KEY DE LICENÇA",9,Ice.Cyan,true);keyCaption.SetBounds(38,377,520,22);Controls.Add(keyCaption);licenseKey.SetBounds(38,405,550,38);licenseKey.Font=Ice.Font(12);licenseKey.BackColor=Ice.Panel;licenseKey.ForeColor=Ice.Text;licenseKey.BorderStyle=BorderStyle.FixedSingle;licenseKey.CharacterCasing=CharacterCasing.Upper;Controls.Add(licenseKey);
  message.Text="Entre com a conta criada anteriormente. A conta permanece vinculada ao primeiro computador.";message.ForeColor=Ice.Muted;message.SetBounds(39,464,548,63);Controls.Add(message);
  submit.Text="Entrar e continuar";submit.Primary=true;submit.SetBounds(335,548,253,47);submit.Click+=async(s,e)=>await Submit();Controls.Add(submit);var exit=new IceButton{Text="Sair",DialogResult=DialogResult.Cancel};exit.SetBounds(38,548,130,47);Controls.Add(exit);CancelButton=exit;AcceptButton=submit;SetMode(false);
 }
 Label MakeLabel(string text,float size,Color color,bool bold=false){return new Label{Text=text,Font=Ice.Font(size,bold),ForeColor=color,BackColor=Color.Transparent};}
 void AddField(string caption,TextBox field,int x,int y){var l=MakeLabel(caption,9,Ice.Cyan,true);l.SetBounds(x,y,520,22);Controls.Add(l);field.SetBounds(x,y+28,550,38);field.Font=Ice.Font(12);field.BackColor=Ice.Panel;field.ForeColor=Ice.Text;field.BorderStyle=BorderStyle.FixedSingle;Controls.Add(field);}
 void SetMode(bool create){registering=create;loginMode.Active=!create;registerMode.Active=create;loginMode.Invalidate();registerMode.Invalidate();keyCaption.Visible=licenseKey.Visible=create;submit.Text=create?"Criar conta e ativar":"Entrar e continuar";message.ForeColor=Ice.Muted;message.Text=create?"Crie usuário e senha usando uma key ainda não utilizada. A validade começa agora.":"Entre com a conta criada anteriormente. A conta permanece vinculada ao primeiro computador.";}
 async Task Submit(){if(username.Text.Trim().Length<3||password.Text.Length<8){message.ForeColor=Ice.Amber;message.Text="Informe um usuário válido e uma senha com pelo menos 8 caracteres.";return;}if(registering&&licenseKey.Text.Trim().Length<10){message.ForeColor=Ice.Amber;message.Text="Informe a key recebida na compra.";return;}submit.Enabled=false;submit.Text=registering?"Criando conta...":"Entrando...";try{var fields=new Dictionary<string,string>{{"username",username.Text.Trim()},{"password",password.Text}};if(registering)fields["key"]=licenseKey.Text.Trim();var data=await LicenseGate.Request(catalog,registering?"/api/account/register":"/api/account/login",fields);State=new LicenseState();State.token=Convert.ToString(data["token"]);State.username=Convert.ToString(data["username"]);State.plan=Convert.ToString(data["plan"]);State.expiresAt=data.ContainsKey("expiresAt")?Convert.ToString(data["expiresAt"]):null;State.createdAt=data.ContainsKey("createdAt")?Convert.ToString(data["createdAt"]):null;State.lastValidated=DateTime.UtcNow.ToString("o");DialogResult=DialogResult.OK;Close();}catch(Exception ex){message.ForeColor=Ice.Amber;message.Text=ex.Message;}finally{submit.Enabled=true;submit.Text=registering?"Criar conta e ativar":"Entrar e continuar";}}
}
