using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Management;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;

public class LicenseState {public string token,username,plan,expiresAt,createdAt,lastValidated;}
public static class LicenseGate {
 static readonly string folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ice optimizer"),file=Path.Combine(folder,"account.dat");
 public static LicenseState Current{get;private set;}
 internal static string Device(){string machine="";try{using(var k=Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Cryptography"))machine=Convert.ToString(k.GetValue("MachineGuid"));}catch{}return Fingerprint(machine+"|"+Environment.MachineName);}
 static string Wmi(string query,string property){try{using(var search=new ManagementObjectSearcher(query))foreach(ManagementObject item in search.Get()){var value=Convert.ToString(item[property]).Trim();if(value.Length>0&&value!="To Be Filled By O.E.M.")return value;}}catch{}return "";}
 internal static string Hardware(){string uuid=Wmi("SELECT UUID FROM Win32_ComputerSystemProduct","UUID"),bios=Wmi("SELECT SerialNumber FROM Win32_BIOS","SerialNumber"),board=Wmi("SELECT SerialNumber FROM Win32_BaseBoard","SerialNumber"),cpu=Wmi("SELECT ProcessorId FROM Win32_Processor","ProcessorId");return Fingerprint("ICE-HW2|"+uuid+"|"+bios+"|"+board+"|"+cpu);}
 static string Fingerprint(string value){using(var h=SHA256.Create())return Convert.ToBase64String(h.ComputeHash(Encoding.UTF8.GetBytes(value)));}
 static LicenseState Read(){try{var enc=File.ReadAllBytes(file);var raw=ProtectedData.Unprotect(enc,null,DataProtectionScope.CurrentUser);return new JavaScriptSerializer().Deserialize<LicenseState>(Encoding.UTF8.GetString(raw));}catch{return null;}}
 static void Save(LicenseState state){Directory.CreateDirectory(folder);var raw=Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(state));File.WriteAllBytes(file,ProtectedData.Protect(raw,null,DataProtectionScope.CurrentUser));}
 static LicenseState StateFrom(Dictionary<string,object> data,LicenseState state=null){state=state??new LicenseState();if(data.ContainsKey("token")&&data["token"]!=null)state.token=Convert.ToString(data["token"]);if(data.ContainsKey("username"))state.username=Convert.ToString(data["username"]);if(data.ContainsKey("plan"))state.plan=Convert.ToString(data["plan"]);state.expiresAt=data.ContainsKey("expiresAt")?Convert.ToString(data["expiresAt"]):null;if(data.ContainsKey("createdAt"))state.createdAt=Convert.ToString(data["createdAt"]);state.lastValidated=DateTime.UtcNow.ToString("o");return state;}
 internal static async Task<Dictionary<string,object>> Request(Catalog catalog,string endpoint,Dictionary<string,string> fields,string token=null){using(var c=new HttpClient{Timeout=TimeSpan.FromSeconds(15)}){c.DefaultRequestHeaders.Add("User-Agent","ice-optimizer/2.3");if(!string.IsNullOrEmpty(token))c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);fields["deviceId"]=Device();fields["hardwareId"]=Hardware();var body=new JavaScriptSerializer().Serialize(fields);using(var response=await c.PostAsync(catalog.licenseApi+endpoint,new StringContent(body,Encoding.UTF8,"application/json"))){var text=await response.Content.ReadAsStringAsync();var data=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(text);if(!response.IsSuccessStatusCode)throw new InvalidOperationException(data!=null&&data.ContainsKey("message")?Convert.ToString(data["message"]):"Acesso recusado.");return data;}}}
 public static bool Ensure(Catalog catalog){var state=Read();if(state!=null&&!string.IsNullOrWhiteSpace(state.token)){try{var r=Request(catalog,"/api/account/profile",new Dictionary<string,string>(),state.token).GetAwaiter().GetResult();Current=StateFrom(r,state);Save(Current);return true;}catch(HttpRequestException){DateTime last;if(DateTime.TryParse(state.lastValidated,out last)&&DateTime.UtcNow-last.ToUniversalTime()<TimeSpan.FromHours(72)&&(string.IsNullOrEmpty(state.expiresAt)||DateTime.Parse(state.expiresAt).ToUniversalTime()>DateTime.UtcNow)){Current=state;return true;}}catch(TaskCanceledException){DateTime last;if(DateTime.TryParse(state.lastValidated,out last)&&DateTime.UtcNow-last.ToUniversalTime()<TimeSpan.FromHours(72)){Current=state;return true;}}catch{}}
  using(var form=new AccountForm(catalog,state==null?"":state.username)){if(form.ShowDialog()!=DialogResult.OK)return false;Current=form.State;Save(Current);return true;}}
 public static string PlanName(string plan){return plan=="d30"?"30 dias":plan=="d90"?"90 dias":plan=="m6"?"6 meses":plan=="permanent"?"Permanente":"Licença";}
 public static string Remaining(LicenseState s){if(s==null)return "Indisponível";if(string.IsNullOrEmpty(s.expiresAt))return "Acesso permanente";DateTime end;if(!DateTime.TryParse(s.expiresAt,out end))return "Indisponível";var left=end.ToUniversalTime()-DateTime.UtcNow;if(left<=TimeSpan.Zero)return "Expirada";if(left.TotalDays>=1)return Math.Ceiling(left.TotalDays)+" dias restantes";return Math.Max(1,Math.Ceiling(left.TotalHours))+" horas restantes";}
}
public class AccountForm:Form {
 readonly Catalog catalog;readonly IceSurface card=new IceSurface(),art=new IceSurface();readonly SnowCanvas snow=new SnowCanvas();TextBox username=new TextBox(),password=new TextBox(),licenseKey=new TextBox();Label message=new Label(),keyCaption=new Label();IceButton submit=new IceButton(),loginMode=new IceButton(),registerMode=new IceButton();bool registering;public LicenseState State;
 public AccountForm(Catalog c,string previous){catalog=c;Text="Conta Ice Optimizer";ClientSize=new Size(930,650);StartPosition=FormStartPosition.CenterScreen;BackColor=Ice.Bg;ForeColor=Ice.Text;Font=Ice.Font(10);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;using(var s=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("ice.ico"))if(s!=null)Icon=new Icon(s);
  snow.Dock=DockStyle.Fill;Controls.Add(snow);art.SetBounds(30,30,330,590);card.SetBounds(386,30,514,590);Controls.Add(art);Controls.Add(card);snow.SendToBack();art.BringToFront();card.BringToFront();
  art.Paint+=DrawArt;var crystal=new Panel{BackColor=Color.Transparent};crystal.SetBounds(91,62,145,145);crystal.Paint+=(s,e)=>Ice.Crystal(e.Graphics,new RectangleF(20,8,105,125),Motion.Phase);art.Controls.Add(crystal);var brand=MakeLabel("ICE OPTIMIZER",23,Ice.Text,true);brand.TextAlign=ContentAlignment.MiddleCenter;brand.SetBounds(25,222,280,42);art.Controls.Add(brand);var edition=MakeLabel("EDIÇÃO GLACIAL  /  POR MACIOTA",8,Ice.Cyan,true);edition.TextAlign=ContentAlignment.MiddleCenter;edition.SetBounds(20,269,290,26);art.Controls.Add(edition);var pitch=MakeLabel("Seu plano. Seu Windows.\nControle claro antes de cada ajuste.",11,Ice.Muted);pitch.TextAlign=ContentAlignment.MiddleCenter;pitch.SetBounds(35,321,260,74);art.Controls.Add(pitch);var security=MakeLabel("✓ Conta protegida\n✓ Licença vinculada\n✓ Histórico local",10,Ice.Text);security.SetBounds(68,441,210,90);art.Controls.Add(security);
  var eyebrow=MakeLabel("ACESSO SEGURO",8.5f,Ice.Cyan,true);eyebrow.SetBounds(34,27,400,25);card.Controls.Add(eyebrow);var title=MakeLabel("Bem-vindo de volta",24,Ice.Text,true);title.SetBounds(32,57,440,45);card.Controls.Add(title);var sub=MakeLabel("Entre na sua conta ou use uma key para criar uma.",9.5f,Ice.Muted);sub.SetBounds(34,103,440,30);card.Controls.Add(sub);
  loginMode.Text="Entrar";loginMode.Active=true;loginMode.SetBounds(34,145,211,42);registerMode.Text="Criar conta";registerMode.SetBounds(253,145,226,42);card.Controls.Add(loginMode);card.Controls.Add(registerMode);loginMode.Click+=(s,e)=>SetMode(false);registerMode.Click+=(s,e)=>SetMode(true);
  AddField(card,"NOME DE USUÁRIO",username,34,208);username.Text=previous;AddField(card,"SENHA",password,34,288);password.UseSystemPasswordChar=true;
  keyCaption=MakeLabel("KEY DE LICENÇA",8.5f,Ice.Cyan,true);keyCaption.SetBounds(34,368,420,20);card.Controls.Add(keyCaption);StyleField(licenseKey);licenseKey.SetBounds(34,393,445,38);licenseKey.CharacterCasing=CharacterCasing.Upper;card.Controls.Add(licenseKey);
  message.Text="Use os dados da conta criada anteriormente.";message.ForeColor=Ice.Muted;message.SetBounds(35,444,444,50);card.Controls.Add(message);
  var exit=new IceButton{Text="Sair",DialogResult=DialogResult.Cancel};exit.SetBounds(34,515,116,44);card.Controls.Add(exit);submit.Text="Entrar e continuar";submit.Primary=true;submit.Glyph="arrow";submit.SetBounds(206,515,273,44);submit.Click+=async(s,e)=>await Submit();card.Controls.Add(submit);CancelButton=exit;AcceptButton=submit;SetMode(false);
  Shown+=(s,e)=>{if(Motion.Enabled){Opacity=.08;var timer=new Timer{Interval=18};timer.Tick+=(o,a)=>{Opacity=Math.Min(1,Opacity+.085);if(Opacity>=1){timer.Stop();timer.Dispose();}};timer.Start();}username.Focus();};Motion.Tick+=Pulse;
 }
 void Pulse(){if(Visible){art.Invalidate();}}
 void DrawArt(object sender,PaintEventArgs e){var g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=new Pen(Color.FromArgb(28,Ice.Cyan))){for(int y=25;y<Height;y+=38)g.DrawLine(p,12,y,Width-12,y+(int)(Math.Sin(Motion.Phase+y)*10));for(int x=-40;x<Width;x+=54)g.DrawLine(p,x,Height,x+165,0);}}
 Label MakeLabel(string text,float size,Color color,bool bold=false){return new Label{Text=text,Font=Ice.Font(size,bold),ForeColor=color,BackColor=Color.Transparent};}
 void StyleField(TextBox field){field.Font=Ice.Font(11);field.BackColor=Color.FromArgb(8,21,35);field.ForeColor=Ice.Text;field.BorderStyle=BorderStyle.FixedSingle;}
 void AddField(Control host,string caption,TextBox field,int x,int y){var l=MakeLabel(caption,8.5f,Ice.Cyan,true);l.SetBounds(x,y,420,20);host.Controls.Add(l);StyleField(field);field.SetBounds(x,y+25,445,38);host.Controls.Add(field);}
 void SetMode(bool create){registering=create;loginMode.Active=!create;registerMode.Active=create;loginMode.Invalidate();registerMode.Invalidate();keyCaption.Visible=licenseKey.Visible=create;submit.Text=create?"Criar conta e ativar":"Entrar e continuar";message.ForeColor=Ice.Muted;message.Text=create?"Sua key será usada uma vez e vinculará a conta a este computador.":"Use os dados da conta criada anteriormente.";if(create)licenseKey.Focus();else username.Focus();}
 async Task Submit(){if(username.Text.Trim().Length<3||password.Text.Length<8){message.ForeColor=Ice.Amber;message.Text="Informe um usuário válido e uma senha com pelo menos 8 caracteres.";return;}if(registering&&licenseKey.Text.Trim().Length<10){message.ForeColor=Ice.Amber;message.Text="Informe a key recebida na compra.";return;}submit.Enabled=loginMode.Enabled=registerMode.Enabled=false;submit.Text=registering?"Criando sua conta...":"Validando acesso...";try{var fields=new Dictionary<string,string>{{"username",username.Text.Trim()},{"password",password.Text}};if(registering)fields["key"]=licenseKey.Text.Trim();var data=await LicenseGate.Request(catalog,registering?"/api/account/register":"/api/account/login",fields);State=new LicenseState();State.token=Convert.ToString(data["token"]);State.username=Convert.ToString(data["username"]);State.plan=Convert.ToString(data["plan"]);State.expiresAt=data.ContainsKey("expiresAt")?Convert.ToString(data["expiresAt"]):null;State.createdAt=data.ContainsKey("createdAt")?Convert.ToString(data["createdAt"]):null;State.lastValidated=DateTime.UtcNow.ToString("o");DialogResult=DialogResult.OK;Close();}catch(Exception ex){message.ForeColor=Ice.Amber;message.Text=ex.Message;}finally{submit.Enabled=loginMode.Enabled=registerMode.Enabled=true;submit.Text=registering?"Criar conta e ativar":"Entrar e continuar";}}
 protected override void Dispose(bool disposing){if(disposing)Motion.Tick-=Pulse;base.Dispose(disposing);}
}
