using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;

public class Preferences {public string root;public string[] selection;}
public class RunRecord {public string when,summary,folder;public List<BatchResult> results;}
public class MainWindow:Form {
 readonly Catalog catalog=Catalog.Load();readonly HashSet<string> selected=new HashSet<string>();readonly Dictionary<string,IceButton> nav=new Dictionary<string,IceButton>();
 Panel sidebar=new Panel(),caption=new Panel(),footer=new Panel(),library=new Panel(),history=new Panel(),profile=new Panel();SnowCanvas content=new SnowCanvas();Hero hero=new Hero();HardwareDashboard hardwarePage=new HardwareDashboard();
 CardDeck cards=new CardDeck();IceSurface inspector=new IceSurface();Panel toolsRow=new Panel();
 HardwareSummary hardwareSummary=new HardwareSummary();GameBanner gameBanner=new GameBanner();
 Label categoryTitle=new Label(),categoryHint=new Label(),selectionLabel=new Label(),status=new Label();TextBox search=new SearchField(),logView=new TextBox();
 IceButton selectAll=new IceButton(),clear=new IceButton(),onlySelected=new IceButton(),run=new IceButton(),cancel=new IceButton(),review=new IceButton(),homeNav,historyNav,profileNav;
 IceProgress progress=new IceProgress();ExecutionOverlay execution=new ExecutionOverlay();
 bool busy,cancelRequested,selectedFilter,layingOut,loading=true,transitioning;string category="Windows",page="home",currentLog,lastRunFolder;List<RunRecord> records=new List<RunRecord>();readonly object logLock=new object();
 readonly string dataFolder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ice optimizer");Preferences prefs=new Preferences();
 [DllImport("user32.dll")]static extern bool ReleaseCapture();[DllImport("user32.dll")]static extern IntPtr SendMessage(IntPtr h,int msg,IntPtr w,IntPtr l);
 public MainWindow(){
  SetStyle(ControlStyles.UserPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.AllPaintingInWmPaint|ControlStyles.ResizeRedraw,true);Text="ice optimizer — por Maciota";FormBorderStyle=FormBorderStyle.None;BackColor=Ice.Bg;ForeColor=Ice.Text;Font=Ice.Font(10);MinimumSize=new Size(1180,760);var work=Screen.PrimaryScreen.WorkingArea;Size=new Size((int)(work.Width*.94),(int)(work.Height*.94));StartPosition=FormStartPosition.CenterScreen;AutoScaleMode=AutoScaleMode.None;
  using(var stream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("ice.ico")){if(stream!=null)Icon=new Icon(stream);}
  ReadPreferences();Motion.Set(true);foreach(var id in prefs.selection??new string[0])if(catalog.actions.Any(a=>a.id==id))selected.Add(id);
  caption.BackColor=Ice.Bg;Controls.Add(caption);caption.MouseDown+=(s,e)=>{if(e.Button==MouseButtons.Left){ReleaseCapture();SendMessage(Handle,0xA1,(IntPtr)2,IntPtr.Zero);}};caption.DoubleClick+=(s,e)=>ToggleMaximize();
  caption.Paint+=(s,e)=>Ice.TextAt(e.Graphics,"ICE OPTIMIZER    /    POR MACIOTA",new Rectangle(23,0,500,38),8,Ice.Muted,true);
  AddWindowButton("—",()=>WindowState=FormWindowState.Minimized,144);AddWindowButton("□",ToggleMaximize,96);AddWindowButton("×",Close,48);
  sidebar.BackColor=Ice.Side;Controls.Add(sidebar);sidebar.Paint+=DrawSidebar;
  homeNav=new IceButton{Text="Início",Glyph="Histórico",BackColor=Ice.Side};homeNav.SetBounds(16,112,180,38);homeNav.Click+=(s,e)=>SwitchPage("home");sidebar.Controls.Add(homeNav);
  string[] cats={"Windows","Jogos","Hardware","Reparos","Aplicativos","Ativações","Recuperação"};int y=153;
  foreach(string cat in cats){var b=new IceButton{Text=cat+"   "+catalog.actions.Count(a=>a.category==cat),Glyph=cat,BackColor=Ice.Side};b.SetBounds(16,y,180,38);string captured=cat;b.Click+=(s,e)=>ChangeCategory(captured);sidebar.Controls.Add(b);nav[cat]=b;y+=41;}
  historyNav=new IceButton{Text="Histórico",Glyph="Histórico",BackColor=Ice.Side};profileNav=new IceButton{Text="Minha conta",Glyph="Perfil",BackColor=Ice.Side};sidebar.Controls.Add(historyNav);sidebar.Controls.Add(profileNav);historyNav.Click+=(s,e)=>{RenderHistory();SwitchPage("history");};profileNav.Click+=(s,e)=>{RenderProfile();SwitchPage("profile");};
  Controls.Add(content);content.Controls.Add(hero);content.Controls.Add(library);content.Controls.Add(hardwarePage);content.Controls.Add(history);content.Controls.Add(profile);library.BackColor=history.BackColor=profile.BackColor=Color.Transparent;
  library.Controls.Add(categoryTitle);library.Controls.Add(categoryHint);StyleLabel(categoryTitle,19,Ice.Text,true);StyleLabel(categoryHint,9,Ice.Muted);
  var searchBox=new IceInput(search){Padding=new Padding(40,11,14,8)};searchBox.SetBounds(0,0,290,40);searchBox.Paint+=(s,e)=>Ice.Icon(e.Graphics,"search",new Rectangle(13,11,18,18),search.Focused?Ice.Cyan:Ice.Muted);searchBox.Tag="search";
  search.BorderStyle=BorderStyle.None;search.BackColor=Ice.Panel;search.ForeColor=Ice.Text;search.Dock=DockStyle.Fill;search.AccessibleName="Buscar ações";searchBox.Controls.Add(search);library.Controls.Add(searchBox);
  library.Controls.Add(toolsRow);selectAll.Text="Marcar categoria";selectAll.Glyph="check";clear.Text="Limpar categoria";onlySelected.Text="Só selecionadas";toolsRow.Controls.Add(selectAll);toolsRow.Controls.Add(clear);toolsRow.Controls.Add(onlySelected);
  selectAll.Click+=(s,e)=>{foreach(var a in catalog.actions.Where(a=>a.category==category))selected.Add(a.id);RefreshSelection();};
  clear.Click+=(s,e)=>{foreach(var a in catalog.actions.Where(a=>a.category==category))selected.Remove(a.id);RefreshSelection();};
  onlySelected.Click+=(s,e)=>{selectedFilter=!selectedFilter;Filter();};
  cards.BackColor=Ice.Bg;cards.Padding=new Padding(0);library.Controls.Add(cards);library.Controls.Add(hardwareSummary);library.Controls.Add(gameBanner);hardwareSummary.Visible=false;gameBanner.Visible=false;
  library.Controls.Add(inspector);inspector.Interactive=true;inspector.Paint+=DrawPlan;review.Text="Revisar plano";review.Glyph="arrow";review.BackColor=Ice.Panel;review.Click+=(s,e)=>ReviewPlan();inspector.Controls.Add(review);
  Controls.Add(footer);footer.BackColor=Ice.Side;footer.Controls.Add(selectionLabel);footer.Controls.Add(status);StyleLabel(selectionLabel,11,Ice.Text,true);StyleLabel(status,9,Ice.Muted);
  run.Text="Revisar e executar";run.Primary=true;run.Glyph="play";run.BackColor=Ice.Side;run.Click+=async(s,e)=>await StartBatch();footer.Controls.Add(run);
  cancel.Text="Parar após esta ação";cancel.BackColor=Ice.Side;cancel.Visible=false;cancel.Click+=(s,e)=>{cancelRequested=true;cancel.Enabled=false;status.Text="Parada solicitada · aguardando a ação atual";};footer.Controls.Add(cancel);footer.Controls.Add(progress);
  BuildHistory();BuildProfile();search.TextChanged+=(s,e)=>Filter();Controls.Add(execution);execution.Dock=DockStyle.Fill;execution.Visible=false;
  KeyPreview=true;KeyDown+=(s,e)=>{if(busy&&e.KeyCode==Keys.Escape){cancelRequested=true;execution.Detail="Parada solicitada · aguardando a ação atual terminar com segurança";execution.Invalidate();e.SuppressKeyPress=true;}else if(e.Control&&e.KeyCode==Keys.F){SwitchPage("library");search.Focus();e.SuppressKeyPress=true;}};
  FormClosing+=(s,e)=>{if(busy){e.Cancel=true;Notify("Uma ação está em andamento","Use Parar após esta ação. A fila encerra ao terminar a ação atual.");}};
  Shown+=(s,e)=>{if(Motion.Enabled){Opacity=.1;var intro=new Timer{Interval=20};intro.Tick+=(o,a)=>{Opacity=Math.Min(1,Opacity+.09);if(Opacity>=1){intro.Stop();intro.Dispose();}};intro.Start();}};
  loading=false;Filter();SwitchPage("home");LayoutApp();
 }
 void AddWindowButton(string text,Action click,int right){var b=new IceButton{Text=text,Width=42,Height=28,Tag=right};b.Click+=(s,e)=>click();caption.Controls.Add(b);}
 void ToggleMaximize(){if(WindowState==FormWindowState.Maximized)WindowState=FormWindowState.Normal;else{MaximizedBounds=Screen.FromControl(this).WorkingArea;WindowState=FormWindowState.Maximized;}}
 protected override void WndProc(ref Message m){base.WndProc(ref m);if(m.Msg==0x84&&WindowState==FormWindowState.Normal){Point p=PointToClient(new Point((int)((long)m.LParam&0xffff),(int)(((long)m.LParam>>16)&0xffff)));int edge=6;bool l=p.X<edge,r=p.X>=Width-edge,t=p.Y<edge,b=p.Y>=Height-edge;int hit=t?(l?13:r?14:12):b?(l?16:r?17:15):l?10:r?11:0;if(hit!=0)m.Result=(IntPtr)hit;}}
 protected override void OnResize(EventArgs e){base.OnResize(e);LayoutApp();}
 protected override void OnPaintBackground(PaintEventArgs e){Ice.DrawCover(e.Graphics,Ice.Scene,ClientRectangle);using(var veil=new SolidBrush(Color.FromArgb(42,0,7,17)))e.Graphics.FillRectangle(veil,ClientRectangle);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;int mx=Math.Max(30,(int)(ClientSize.Width*.065)),top=Math.Max(92,(int)(ClientSize.Height*.115)),bottom=38;var frame=new Rectangle(mx,top,ClientSize.Width-mx*2,ClientSize.Height-top-bottom);for(int i=12;i>=1;i-=2)using(var p=new Pen(Color.FromArgb(8+(12-i)*2,Ice.Cyan),i))using(var gp=Ice.Round(new RectangleF(frame.X-i/2f,frame.Y-i/2f,frame.Width+i,frame.Height+i),18))g.DrawPath(p,gp);using(var p=new Pen(Color.FromArgb(225,83,207,255),2))using(var gp=Ice.Round(frame,18))g.DrawPath(p,gp);Ice.Crystal(g,new RectangleF(ClientSize.Width/2-215,12,64,78),Motion.Phase);Ice.TextAt(g,"ICE OPTIMIZER",new Rectangle(ClientSize.Width/2-135,17,330,48),25,Ice.Text,true);Ice.TextAt(g,"DESEMPENHO REAL. SEM COMPLICAÇÃO.",new Rectangle(ClientSize.Width/2-132,61,330,22),8.5f,Ice.Cyan,true);Ice.TextAt(g,"OTIMIZE  ·  JOGUE  ·  PRODUZA  ·  SEM LIMITES.",new Rectangle(34,30,310,45),8.5f,Color.FromArgb(82,197,242),true);Ice.TextAt(g,"MAIS PERFORMANCE PARA O SEU MUNDO",new Rectangle(ClientSize.Width/2-220,ClientSize.Height-31,440,22),8,Color.FromArgb(105,199,240),true);}
 void LayoutApp(){if(loading||layingOut||content==null||sidebar==null||footer==null)return;layingOut=true;try{
  int mx=Math.Max(30,(int)(ClientSize.Width*.065)),top=Math.Max(92,(int)(ClientSize.Height*.115)),bottom=38,fw=ClientSize.Width-mx*2,fh=ClientSize.Height-top-bottom,side=225;
  caption.SetBounds(mx+2,top+2,fw-4,40);foreach(Control c in caption.Controls)if(c.Tag is int)c.SetBounds(caption.Width-(int)c.Tag,6,42,28);
  sidebar.SetBounds(mx+2,top+43,side,fh-45);historyNav.SetBounds(18,sidebar.Height-164,188,42);profileNav.SetBounds(18,sidebar.Height-113,188,42);
  content.SetBounds(mx+side+24,top+58,Math.Max(620,fw-side-48),Math.Max(500,fh-158));hero.SetBounds(0,0,content.Width,content.Height);
  library.SetBounds(0,0,content.Width,content.Height);hardwarePage.SetBounds(0,0,content.Width,content.Height);history.SetBounds(0,0,content.Width,content.Height);profile.SetBounds(0,0,content.Width,content.Height);
  bool showPlan=content.Width>=1020;inspector.Visible=showPlan;int gridWidth=showPlan?library.Width-286:library.Width;
  inspector.SetBounds(library.Width-266,0,266,Math.Min(library.Height-3,490));review.SetBounds(18,inspector.Height-60,230,40);
  categoryTitle.SetBounds(0,0,gridWidth-305,34);categoryHint.SetBounds(0,37,gridWidth,23);
  foreach(Control c in library.Controls)if((string)c.Tag=="search")c.SetBounds(gridWidth-285,0,285,39);
  toolsRow.SetBounds(0,70,gridWidth,40);selectAll.SetBounds(0,0,164,38);clear.SetBounds(173,0,155,38);onlySelected.SetBounds(337,0,155,38);
  bool games=category=="Jogos";gameBanner.Visible=games;gameBanner.SetBounds(0,0,gridWidth,148);hardwareSummary.Visible=false;int headY=games?160:0;categoryTitle.SetBounds(0,headY,gridWidth-305,34);categoryHint.SetBounds(0,headY+37,gridWidth,23);foreach(Control c in library.Controls)if((string)c.Tag=="search")c.SetBounds(gridWidth-285,headY,285,39);toolsRow.SetBounds(0,headY+70,gridWidth,40);int listTop=games?284:124;cards.SetBounds(0,listTop,gridWidth,Math.Max(120,library.Height-listTop));ResizeCards();
  footer.SetBounds(mx+side+2,top+fh-87,fw-side-4,84);selectionLabel.SetBounds(24,10,footer.Width-300,25);status.SetBounds(24,37,footer.Width-300,24);run.SetBounds(footer.Width-245,13,220,47);cancel.SetBounds(footer.Width-245,13,220,47);progress.SetBounds(24,67,footer.Width-48,12);execution.SetBounds(0,0,ClientSize.Width,ClientSize.Height);if(execution.Visible)execution.BringToFront();
  LayoutHistory();LayoutProfile();
 }finally{layingOut=false;}}
 void ResizeCards(){cards.LayoutCards();}
 void DrawSidebar(object sender,PaintEventArgs e){var g=e.Graphics;Ice.Crystal(g,new RectangleF(20,17,43,58));Ice.TextAt(g,"ICE",new Rectangle(75,15,115,37),21,Ice.Text,true);Ice.TextAt(g,"OPTIMIZER",new Rectangle(76,49,116,22),9,Ice.Cyan,true);using(var pen=new Pen(Ice.Line))g.DrawLine(pen,24,sidebar.Height-180,187,sidebar.Height-180);Ice.TextAt(g,"POR MACIOTA     /     v"+catalog.version.Substring(0,3),new Rectangle(27,sidebar.Height-44,180,24),8,Ice.Muted,true);}
 void DrawPlan(object sender,PaintEventArgs e){var g=e.Graphics;var plan=Chosen();Ice.TextAt(g,"SEU PLANO",new Rectangle(20,17,230,24),9,Ice.Muted,true);Ice.TextAt(g,plan.Length.ToString("00"),new Rectangle(19,54,210,62),40,Ice.Cyan,true);Ice.TextAt(g,"ações selecionadas",new Rectangle(23,119,216,26),11,Ice.Text);int risks=plan.Count(a=>a.risk=="Alto impacto");Ice.TextAt(g,risks+" de alto impacto  ·  "+plan.Count(a=>a.restart)+" pedem reinício",new Rectangle(23,158,220,42),9,risks>0?Ice.Amber:Ice.Muted,false,true);
  using(var pen=new Pen(Ice.Line))g.DrawLine(pen,22,214,243,214);if(plan.Length==0)Ice.TextAt(g,"Marque os cartões para montar sua fila de execução.",new Rectangle(23,237,220,70),11,Ice.Muted,false,true);else{int y=235;foreach(var a in plan.Take(3)){Ice.TextAt(g,"• "+a.title,new Rectangle(23,y,218,35),9,Ice.Text,false,true);y+=41;}if(plan.Length>3)Ice.TextAt(g,"+ "+(plan.Length-3)+" ações no plano",new Rectangle(23,y,220,26),9,Ice.Cyan);}
  var problems=BatchPlan.Problems(plan);if(plan.Length>0&&problems.Count>0)Ice.TextAt(g,"Revise combinações antes de executar.",new Rectangle(23,inspector.Height-105,218,38),9,Ice.Amber,false,true);
 }
 void StyleLabel(Label l,float size,Color color,bool bold=false){l.Font=Ice.Font(size,bold);l.ForeColor=color;l.BackColor=Color.Transparent;}
 Label Label(string text,float size=10,Color? color=null,bool bold=false){var l=new Label{Text=text};StyleLabel(l,size,color??Ice.Text,bold);return l;}
 ActionItem[] Chosen(){return BatchPlan.Order(catalog.actions.Where(a=>selected.Contains(a.id)));}
 Control[] PageControls(string name){return name=="home"?new Control[]{hero}:name=="hardware"?new Control[]{hardwarePage}:name=="library"?new Control[]{library}:name=="history"?new Control[]{history}:new Control[]{profile};}
 int PageRank(string name){return name=="home"?0:name=="library"?1:name=="hardware"?2:name=="history"?3:4;}
 void PlacePage(string name,int offset){foreach(var c in PageControls(name))c.SetBounds(offset,0,content.Width,content.Height);}
 void UpdateNavigation(){bool lib=page=="library";homeNav.Active=page=="home";homeNav.Invalidate();foreach(var pair in nav){pair.Value.Active=(lib&&pair.Key==category)||(page=="hardware"&&pair.Key=="Hardware");pair.Value.Invalidate();}historyNav.Active=page=="history";profileNav.Active=page=="profile";historyNav.Invalidate();profileNav.Invalidate();footer.Visible=lib;}
 void SwitchPage(string name){var all=new Control[]{hero,library,hardwarePage,history,profile};if(transitioning||name==page){page=name;foreach(var c in all)c.Visible=PageControls(name).Contains(c);UpdateNavigation();LayoutApp();return;}string old=page;int direction=PageRank(name)>=PageRank(old)?1:-1;var oldFrame=SlideTransition.Snapshot(content);page=name;foreach(var c in all)c.Visible=PageControls(name).Contains(c);UpdateNavigation();LayoutApp();foreach(var c in PageControls(name))c.BringToFront();var newFrame=SlideTransition.Snapshot(content);foreach(var c in all)c.Visible=false;var slide=new SlideTransition(oldFrame,newFrame,direction){BackColor=Ice.Bg,Dock=DockStyle.Fill};content.Controls.Add(slide);slide.BringToFront();transitioning=true;var watch=Stopwatch.StartNew();var timer=new Timer{Interval=15};timer.Tick+=(s,e)=>{float t=Math.Min(1f,(float)watch.Elapsed.TotalMilliseconds/260f);slide.SetProgress(t);if(t>=1){timer.Stop();timer.Dispose();content.Controls.Remove(slide);slide.Dispose();foreach(var c in PageControls(name)){c.Visible=true;c.BringToFront();}PlacePage(name,0);transitioning=false;}};timer.Start();}
 void ChangeCategory(string next){if(busy||transitioning)return;if(next=="Hardware"){category=next;SwitchPage("hardware");return;}if(page!="library"){category=next;selectedFilter=false;search.Clear();Filter();SwitchPage("library");return;}if(next==category)return;var order=new[]{"Windows","Jogos","Hardware","Reparos","Aplicativos","Ativações","Recuperação"};int direction=Array.IndexOf(order,next)>Array.IndexOf(order,category)?1:-1;transitioning=true;var oldFrame=SlideTransition.Snapshot(library);category=next;selectedFilter=false;search.Clear();Filter();UpdateNavigation();var newFrame=SlideTransition.Snapshot(library);library.Visible=false;var slide=new SlideTransition(oldFrame,newFrame,direction){BackColor=Ice.Bg};slide.SetBounds(library.Bounds.X,library.Bounds.Y,library.Width,library.Height);content.Controls.Add(slide);slide.BringToFront();var watch=Stopwatch.StartNew();var timer=new Timer{Interval=15};timer.Tick+=(s,e)=>{float t=Math.Min(1f,(float)watch.Elapsed.TotalMilliseconds/240f);slide.SetProgress(t);if(t>=1){timer.Stop();timer.Dispose();content.Controls.Remove(slide);slide.Dispose();library.Visible=true;library.BringToFront();PlacePage("library",0);transitioning=false;}};timer.Start();}
 void Filter(){cards.SuspendLayout();foreach(Control c in cards.Controls.Cast<Control>().ToArray()){cards.Controls.Remove(c);c.Dispose();}
  string q=search.Text.Trim();var source=catalog.actions.Where(a=>a.category==category&&(!selectedFilter||selected.Contains(a.id))&&(a.title+" "+a.description).IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0).ToArray();
  foreach(var a in source){var card=new ActionCard(a){Checked=selected.Contains(a.id),Enabled=!busy};card.Toggle+=c=>{if(selected.Contains(c.Item.id))selected.Remove(c.Item.id);else selected.Add(c.Item.id);RefreshSelection(false);};card.Details+=c=>ShowDetails(c.Item);cards.Controls.Add(card);}
  if(source.Length==0){var empty=Label("Nenhuma ação encontrada.\nTente outro termo ou desative o filtro de selecionadas.",12,Ice.Muted);empty.Height=120;cards.Controls.Add(empty);}
  cards.ResumeLayout();cards.ResetScroll();categoryTitle.Text=category;categoryHint.Text=source.Length+" ações exibidas · busque por nome ou função";onlySelected.Active=selectedFilter;onlySelected.Invalidate();ResizeCards();RefreshSelection(false);
  gameBanner.Visible=category=="Jogos";LayoutApp();
 }
 void RefreshSelection(bool refilter=true){if(refilter){Filter();return;}foreach(var card in cards.Controls.OfType<ActionCard>()){card.Checked=selected.Contains(card.Item.id);card.Invalidate();}var plan=Chosen();selectionLabel.Text=plan.Length==0?"Seu próximo ajuste começa com uma escolha.":plan.Length+" ações no plano  ·  "+plan.Select(a=>a.category).Distinct().Count()+" categorias";if(!busy)status.Text=plan.Length==0?"Marque uma ação ou toda a categoria para começar.":BatchPlan.Problems(plan).Count>0?"Há combinações para revisar antes de executar.":"Pronto para revisar · nenhuma alteração aplicada.";run.Enabled=plan.Length>0&&!busy;review.Enabled=plan.Length>0&&!busy;inspector.Invalidate();}
 Form Dialog(string title,int width=680,int height=530){var d=new Form{Text=title,Size=new Size(width,height),MinimumSize=new Size(width,height),StartPosition=FormStartPosition.CenterParent,BackColor=Ice.Bg,ForeColor=Ice.Text,Font=Ice.Font(10),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,ShowInTaskbar=false};if(Icon!=null)d.Icon=Icon;return d;}
 void Notify(string title,string text){using(var d=Dialog(title,650,410)){var h=Label(title,20,Ice.Cyan,true);h.SetBounds(24,25,590,62);d.Controls.Add(h);var p=Label(text,11,Ice.Text);p.SetBounds(26,110,586,175);d.Controls.Add(p);var ok=new IceButton{Text="Entendi",Primary=true,DialogResult=DialogResult.OK};ok.SetBounds(440,305,166,42);d.Controls.Add(ok);d.AcceptButton=ok;d.ShowDialog(this);}}
 void ShowDetails(ActionItem a){using(var d=Dialog(a.title,690,560)){var t=Label(a.title,21,Ice.Text,true);t.SetBounds(25,24,623,74);d.Controls.Add(t);var badge=Label(a.category+"  /  "+a.risk+(a.standalone?"  /  Execução separada":""),10,Ice.Cyan,true);badge.SetBounds(27,111,615,35);d.Controls.Add(badge);var desc=Label(a.description,11,Ice.Text);desc.SetBounds(27,163,615,134);d.Controls.Add(desc);var w=Label(a.warning,11,Ice.Amber);w.SetBounds(27,310,615,121);d.Controls.Add(w);var toggle=new IceButton{Text=selected.Contains(a.id)?"Remover do plano":"Adicionar ao plano",Primary=true,Enabled=!busy};toggle.SetBounds(405,454,230,42);toggle.Click+=(s,e)=>{if(selected.Contains(a.id))selected.Remove(a.id);else selected.Add(a.id);RefreshSelection();d.Close();};d.Controls.Add(toggle);var close=new IceButton{Text="Voltar",DialogResult=DialogResult.Cancel};close.SetBounds(27,454,130,42);d.Controls.Add(close);d.CancelButton=close;d.ShowDialog(this);}}
 bool ReviewPlan(bool confirm=false){var plan=Chosen();using(var d=Dialog("Revise seu plano",820,650)){
  var title=Label("Revise seu plano",23,Ice.Text,true);title.SetBounds(26,22,735,48);d.Controls.Add(title);var sub=Label("Desmarque itens para ajustar a fila. O ponto de restauração, se escolhido, vem primeiro.",10,Ice.Muted);sub.SetBounds(28,79,740,40);d.Controls.Add(sub);
  var checklist=new CheckedListBox{BackColor=Ice.Panel,ForeColor=Ice.Text,BorderStyle=BorderStyle.None,CheckOnClick=true,Font=Ice.Font(10)};checklist.SetBounds(28,133,742,230);foreach(var a in plan)checklist.Items.Add(a,true);d.Controls.Add(checklist);
  var issues=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,BorderStyle=BorderStyle.None,BackColor=Ice.Bg,ForeColor=Ice.Amber,Font=Ice.Font(10)};issues.SetBounds(28,382,742,128);d.Controls.Add(issues);
  var apply=new IceButton{Text=confirm?"Confirmar execução":"Salvar seleção",Primary=true};apply.SetBounds(535,541,235,44);d.Controls.Add(apply);
  Action update=()=>{var chosen=checklist.CheckedItems.Cast<ActionItem>().ToArray();var problems=BatchPlan.Problems(chosen);issues.Text=problems.Count>0?string.Join(Environment.NewLine,problems):string.Join(Environment.NewLine,chosen.Where(a=>a.risk=="Alto impacto").Select(a=>a.title+": "+a.warning));if(issues.Text.Length==0)issues.Text="Os scripts serão preparados antes de aplicar mudanças. Revise o registro ao concluir.";apply.Enabled=!confirm||problems.Count==0;};
  checklist.ItemCheck+=(s,e)=>d.BeginInvoke(update);apply.Click+=(s,e)=>{selected.Clear();foreach(ActionItem a in checklist.CheckedItems)selected.Add(a.id);RefreshSelection();d.DialogResult=DialogResult.OK;d.Close();};
  var back=new IceButton{Text="Voltar",DialogResult=DialogResult.Cancel};back.SetBounds(28,541,145,44);d.Controls.Add(back);d.CancelButton=back;update();return d.ShowDialog(this)==DialogResult.OK;
 }}
 void SetBusy(bool value){busy=value;run.Visible=!value;cancel.Visible=false;selectAll.Enabled=clear.Enabled=onlySelected.Enabled=!value;foreach(var c in cards.Controls.OfType<ActionCard>())c.Enabled=!value;review.Enabled=!value;progress.Running=value;execution.Visible=value;if(value){execution.Value=0;execution.Detail="Preparando os arquivos com verificação de integridade...";execution.BringToFront();execution.Focus();execution.Refresh();}RefreshSelection(false);}
 async Task StartBatch(){if(busy||Chosen().Length==0)return;if(!ReviewPlan(true))return;
  if(!new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator)){Notify("Permissão necessária","O Ice Optimizer precisa de acesso de administrador para proteger a execução dos ajustes.");return;}
  string configuredRoot=Path.Combine(dataFolder,"Runs");try{Payload.SafeRoot(configuredRoot);}catch(Exception e){Notify("Ambiente indisponível",e.Message);return;}
  var plan=Chosen();string runRoot=Path.Combine(configuredRoot,DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-plano-"+Guid.NewGuid().ToString("N").Substring(0,6));bool local=Directory.Exists(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"scripts"));bool stopOnError=false;
  cancelRequested=false;progress.Value=0;SetBusy(true);List<BatchResult> results=new List<BatchResult>();string summary="";
  try{
   Directory.CreateDirectory(runRoot);lastRunFolder=runRoot;currentLog=Path.Combine(runRoot,"plano.log");Log("ice optimizer 2.6 — por Maciota | "+DateTime.Now.ToString("s"));
   results=await BatchPlan.Run(plan,a=>Payload.Prepare(catalog,a,runRoot,local,null,Log),async(a,script)=>{
    foreach(string file in new[]{a.file}.Concat(a.dependencies))Payload.Verify(File.ReadAllBytes(Payload.Destination(Path.GetDirectoryName(script),file)),catalog.files[file]);
    string actionLog=Path.Combine(Path.GetDirectoryName(script),"execution.log");Log("INICIANDO: "+a.title);
    int code=await Payload.Execute(script,line=>{lock(logLock)File.AppendAllText(actionLog,line+Environment.NewLine,Encoding.UTF8);Log(line);});
    Log("ENCERRADO: "+a.title+" | código "+code+". Revise o registro para falhas parciais.");return code;
   },()=>cancelRequested,(phase,index,total,a)=>{
    status.Text=(phase=="download"?"Preparando ":phase=="execute"?"Executando ":"Encerradas ")+(phase=="complete"?index:index+1)+"/"+total+" · "+a.title;
    float value=phase=="download"?.28f*index/Math.Max(1,total):phase=="execute"?.28f+.72f*index/Math.Max(1,total):.28f+.72f*index/Math.Max(1,total);progress.Value=value;execution.Value=value;execution.Detail=(phase=="download"?"Preparando e verificando: ":phase=="execute"?"Executando com segurança: ":"Concluída: ")+a.title;execution.Invalidate();
   },stopOnError);
   progress.Value=execution.Value=1;execution.Detail="Finalizando registros e preparando o resultado...";execution.Invalidate();if(Motion.Enabled)await Task.Delay(420);
   int errors=results.Count(r=>r.code!=0);summary=cancelRequested?"Fila interrompida após a ação atual.":results.Count<plan.Length?"Fila interrompida após falha.":"Fila encerrada. Revise os registros.";summary+=" "+results.Count+"/"+plan.Length+" ações · "+errors+" com erro informado.";Log(summary);
  }catch(Exception e){summary="Fila interrompida: "+e.Message;Log(summary);}
  finally{
   if(Directory.Exists(runRoot)){var record=new RunRecord{when=DateTime.Now.ToString("dd/MM/yyyy HH:mm"),summary=summary,folder=runRoot,results=results};try{File.WriteAllText(Path.Combine(runRoot,"resultado.json"),new JavaScriptSerializer().Serialize(record));records.Insert(0,record);SaveHistory();}catch(Exception e){Log("Não foi possível salvar o histórico: "+e.Message);}}
   currentLog=null;selected.Clear();SavePreferences();Filter();SetBusy(false);status.Text=summary;RenderHistory();ShowResults(results,plan.Length);
  }
 }
 void ShowResults(List<BatchResult> results,int planned){using(var d=Dialog("Resultado do plano",790,650)){int ok=results.Count(r=>r.code==0),bad=results.Count(r=>r.code!=0),skipped=Math.Max(0,planned-results.Count);var title=Label("Plano concluído",24,Ice.Text,true);title.SetBounds(28,22,700,48);d.Controls.Add(title);var metrics=Label(ok+" funcionaram     "+bad+" deram erro     "+skipped+" não executadas",13,bad>0?Ice.Amber:Ice.Cyan,true);metrics.SetBounds(30,82,710,40);d.Controls.Add(metrics);var list=new ListBox{BackColor=Ice.Panel,ForeColor=Ice.Text,BorderStyle=BorderStyle.None,Font=Ice.Font(10),ItemHeight=31,DrawMode=DrawMode.OwnerDrawFixed};list.SetBounds(30,140,710,355);foreach(var r in results)list.Items.Add(r);list.DrawItem+=(s,e)=>{if(e.Index<0)return;var r=(BatchResult)list.Items[e.Index];e.DrawBackground();Ice.TextAt(e.Graphics,(r.code==0?"✓  ":"×  ")+r.title,new Rectangle(e.Bounds.X+8,e.Bounds.Y,e.Bounds.Width-170,e.Bounds.Height),10,r.code==0?Ice.Text:Ice.Amber,r.code!=0);Ice.TextAt(e.Graphics,r.code==0?"Concluída":"Erro "+r.code,new Rectangle(e.Bounds.Right-150,e.Bounds.Y,135,e.Bounds.Height),9,r.code==0?Ice.Cyan:Ice.Amber);};d.Controls.Add(list);var note=Label("A fila continuou mesmo quando houve erro. Consulte o Histórico para conferir as mensagens de cada comando.",9,Ice.Muted);note.SetBounds(31,512,700,48);d.Controls.Add(note);var done=new IceButton{Text="Concluir",Primary=true,DialogResult=DialogResult.OK};done.SetBounds(565,566,175,43);d.Controls.Add(done);d.AcceptButton=done;d.ShowDialog(this);}}
 void Log(string text){lock(logLock){try{if(currentLog!=null)File.AppendAllText(currentLog,text+Environment.NewLine,Encoding.UTF8);}catch(IOException e){text+=" [Registro em disco indisponível: "+e.Message+"]";}}if(IsHandleCreated&&!IsDisposed)BeginInvoke((Action)(()=>{if(logView.TextLength>150000)logView.Text=logView.Text.Substring(logView.TextLength-90000);logView.AppendText(text+Environment.NewLine);}));}
 void ReadPreferences(){try{string p=Path.Combine(dataFolder,"preferences.json");if(File.Exists(p))prefs=new JavaScriptSerializer().Deserialize<Preferences>(File.ReadAllText(p));string h=Path.Combine(dataFolder,"history.json");if(File.Exists(h))records=new JavaScriptSerializer().Deserialize<List<RunRecord>>(File.ReadAllText(h))??new List<RunRecord>();}catch{prefs=new Preferences();}if(prefs==null)prefs=new Preferences();prefs.root=Path.Combine(dataFolder,"Runs");}
 void SavePreferences(){if(loading)return;prefs.root=Path.Combine(dataFolder,"Runs");prefs.selection=selected.ToArray();try{Directory.CreateDirectory(dataFolder);File.WriteAllText(Path.Combine(dataFolder,"preferences.json"),new JavaScriptSerializer().Serialize(prefs));}catch(Exception e){status.Text="Preferências não salvas: "+e.Message;}}
 void SaveHistory(){Directory.CreateDirectory(dataFolder);File.WriteAllText(Path.Combine(dataFolder,"history.json"),new JavaScriptSerializer().Serialize(records.Take(50).ToList()));}
 void BuildHistory(){var title=Label("Histórico de execução",26,Ice.Text,true);title.SetBounds(0,8,700,48);history.Controls.Add(title);var sub=Label("Acompanhe cada fila e mantenha seus registros por perto.",11,Ice.Muted);sub.SetBounds(2,66,800,32);history.Controls.Add(sub);logView.Multiline=true;logView.ReadOnly=true;logView.ScrollBars=ScrollBars.Both;logView.WordWrap=false;logView.BackColor=Ice.Panel;logView.ForeColor=Ice.Muted;logView.BorderStyle=BorderStyle.None;logView.Font=new Font("Consolas",9);history.Controls.Add(logView);
  var open=new IceButton{Text="Abrir pasta de registros",Glyph="Histórico",Tag="openLogs"};open.Click+=(s,e)=>{var folder=lastRunFolder??(records.Count>0?records[0].folder:Path.Combine(dataFolder,"Runs"));if(Directory.Exists(folder))Process.Start(new ProcessStartInfo(folder){UseShellExecute=true});else Notify("Nenhum registro ainda","Execute uma ação para criar registros nesta pasta.");};history.Controls.Add(open);
  RenderHistory();
 }
 void RenderHistory(){if(busy)return;logView.Text=records.Count==0?"Nenhuma execução ainda.\r\n\r\nAs ações só são aplicadas depois que você revisa e confirma o plano.":string.Join("\r\n\r\n",records.Take(50).Select(r=>r.when+"\r\n"+r.summary+"\r\n"+r.folder+"\r\n"+string.Join("\r\n",(r.results??new List<BatchResult>()).Select(x=>"  · "+x.title+" — "+x.status))));}
 void LayoutHistory(){logView.SetBounds(0,119,history.Width,Math.Max(140,history.Height-191));foreach(Control c in history.Controls)if((string)c.Tag=="openLogs")c.SetBounds(0,history.Height-53,263,43);}
 void BuildProfile(){profile.Paint+=(s,e)=>{var g=e.Graphics;using(var glow=new SolidBrush(Color.FromArgb(16,Ice.Blue)))g.FillEllipse(glow,profile.Width-330,-180,480,480);using(var p=new Pen(Color.FromArgb(16,Ice.Cyan))){for(int i=0;i<8;i++)g.DrawLine(p,profile.Width-380+i*58,profile.Height,profile.Width-180+i*35,0);}};
  var crumb=Label("Início   ›   Minha conta",9,Ice.Muted);crumb.Tag="crumb";profile.Controls.Add(crumb);var icon=new Panel{Tag="profileIcon",BackColor=Color.Transparent};icon.Paint+=(s,e)=>Ice.Icon(e.Graphics,"Perfil",new Rectangle(5,5,39,39),Ice.Cyan);profile.Controls.Add(icon);var title=Label("Minha conta",25,Ice.Text,true);title.Tag="profileTitle";profile.Controls.Add(title);var sub=Label("Gerencie sua licença, segurança e acesso.",9,Ice.Muted);sub.Tag="profileSub";profile.Controls.Add(sub);
  var card=new IceSurface{Tag="profileCard",Interactive=true};profile.Controls.Add(card);foreach(var tag in new[]{"avatar","user","plan","remaining","expires","checks"}){var l=Label("",tag=="avatar"?34:tag=="user"?16:tag=="remaining"?11:9,tag=="remaining"?Ice.Cyan:tag=="checks"?Color.FromArgb(139,190,207):Ice.Text,tag=="user"||tag=="remaining");l.Tag=tag;card.Controls.Add(l);}var bar=new IceProgress{Tag="profileProgress"};card.Controls.Add(bar);var change=new IceButton{Text="Alterar senha",Glyph="Recuperação",Tag="changePassword"};change.Click+=(s,e)=>Process.Start(new ProcessStartInfo("https://ice-optimizer-web-production.up.railway.app/"){UseShellExecute=true});card.Controls.Add(change);var logout=new IceButton{Text="Sair da conta",Glyph="arrow",Tag="logout"};logout.ForeColor=Color.FromArgb(255,120,128);logout.Click+=(s,e)=>LogoutAccount();card.Controls.Add(logout);
  var info=new IceSurface{Tag="infoCard"};profile.Controls.Add(info);var infoTitle=Label("Informações da conta",11,Ice.Text,true);infoTitle.Tag="infoTitle";info.Controls.Add(infoTitle);foreach(var tag in new[]{"infoUser","infoPlan","infoStatus","infoExpiry","infoHwid","infoSeen"}){var l=Label("",8.5f,tag=="infoStatus"?Color.FromArgb(95,225,181):Ice.Muted);l.Tag=tag;info.Controls.Add(l);}
  var manage=new IceSurface{Tag="manageCard",Interactive=true};profile.Controls.Add(manage);var mt=Label("Gerenciar licença",11,Ice.Text,true);mt.Tag="manageTitle";manage.Controls.Add(mt);var md=Label("Precisa de um novo plano ou quer renovar seu acesso?",8.5f,Ice.Muted);md.Tag="manageDesc";manage.Controls.Add(md);var mb=new IceButton{Text="Gerenciar / Renovar plano   →",Primary=true,Tag="manageButton"};mb.Click+=(s,e)=>Process.Start(new ProcessStartInfo("https://ice-optimizer-web-production.up.railway.app/#planos"){UseShellExecute=true});manage.Controls.Add(mb);RenderProfile();}
 void LogoutAccount(){if(busy)return;string previous=LicenseGate.Current==null?"":LicenseGate.Current.username;LicenseGate.Logout();Hide();if(!LicenseGate.SignIn(catalog,previous)){Close();return;}RenderProfile();Show();Activate();SwitchPage("library");}
 void RenderProfile(){var s=LicenseGate.Current;if(s==null)return;var card=profile.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="profileCard");var info=profile.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="infoCard");if(card==null||info==null)return;Action<Control,string,string> set=(host,tag,value)=>{var l=host.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag==tag) as Label;if(l!=null)l.Text=value;};DateTime end;bool dated=DateTime.TryParse(s.expiresAt,out end);string remaining=LicenseGate.Remaining(s),expiry=string.IsNullOrEmpty(s.expiresAt)?"Permanente":dated?end.ToLocalTime().ToString("dd/MM/yyyy HH:mm"):"Indisponível";set(card,"avatar","❄");set(card,"user",s.username??"Conta Ice");set(card,"plan","Plano "+LicenseGate.PlanName(s.plan));set(card,"remaining",remaining);set(card,"expires","Válida até "+expiry);set(card,"checks","●  Conta validada neste computador\n\n●  Uso offline disponível por até 72 horas\n\n●  HWID protegido\n\n●  Todas as funcionalidades liberadas");var progressBar=card.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="profileProgress") as IceProgress;if(progressBar!=null)progressBar.Value=s.plan=="permanent"?1f:.84f;set(info,"infoUser","♙   Usuário                         "+s.username);set(info,"infoPlan","▣   Plano                           "+LicenseGate.PlanName(s.plan));set(info,"infoStatus","◉   Status                          Ativa");set(info,"infoExpiry","▣   Válido até                     "+expiry);set(info,"infoHwid","⌾   HWID                            Protegido");set(info,"infoSeen","◷   Último acesso              "+DateTime.Now.ToString("dd/MM/yyyy HH:mm"));}
 void LayoutProfile(){int gap=18,right=Math.Max(330,(profile.Width-18)*47/100),left=profile.Width-gap-right;foreach(Control c in profile.Controls){string tag=Convert.ToString(c.Tag);if(tag=="crumb")c.SetBounds(0,2,500,23);else if(tag=="profileIcon")c.SetBounds(6,38,52,52);else if(tag=="profileTitle")c.SetBounds(58,38,500,38);else if(tag=="profileSub")c.SetBounds(60,75,500,25);}var card=profile.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="profileCard");var info=profile.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="infoCard");var manage=profile.Controls.Cast<Control>().FirstOrDefault(c=>(string)c.Tag=="manageCard");if(card==null||info==null||manage==null)return;card.SetBounds(0,112,left,Math.Min(430,profile.Height-122));info.SetBounds(left+gap,112,right,230);manage.SetBounds(left+gap,356,right,Math.Min(174,profile.Height-366));foreach(Control c in card.Controls){string tag=Convert.ToString(c.Tag);if(tag=="avatar")c.SetBounds(25,19,62,60);else if(tag=="user")c.SetBounds(92,22,left-115,30);else if(tag=="plan")c.SetBounds(94,51,left-116,25);else if(tag=="remaining")c.SetBounds(25,94,left-50,28);else if(tag=="profileProgress")c.SetBounds(25,125,left-50,11);else if(tag=="expires")c.SetBounds(25,145,left-50,25);else if(tag=="checks")c.SetBounds(25,183,left-50,128);else if(tag=="changePassword")c.SetBounds(25,card.Height-60,(left-58)/2,42);else if(tag=="logout")c.SetBounds(33+(left-58)/2,card.Height-60,(left-58)/2,42);}int iy=15;foreach(Control c in info.Controls){string tag=Convert.ToString(c.Tag);if(tag=="infoTitle"){c.SetBounds(17,11,right-34,29);continue;}c.SetBounds(17,iy+=31,right-34,27);}foreach(Control c in manage.Controls){string tag=Convert.ToString(c.Tag);if(tag=="manageTitle")c.SetBounds(17,12,right-34,28);else if(tag=="manageDesc")c.SetBounds(17,44,right-34,43);else if(tag=="manageButton")c.SetBounds(17,manage.Height-57,right-34,40);}profile.Invalidate();}
 public void Render(string file,string mode=""){selected.Clear();Motion.Set(false);if(mode=="hardware"){page="hardware";foreach(var c in new Control[]{hero,library,hardwarePage,history,profile})c.Visible=PageControls(page).Contains(c);UpdateNavigation();}if(mode=="games"){category="Jogos";page="library";foreach(var c in new Control[]{hero,library,hardwarePage,history,profile})c.Visible=PageControls(page).Contains(c);Filter();UpdateNavigation();}if(mode=="selected"){foreach(string id in new[]{"opcao19","opcao21","opcao31","opcao32","restore","limparram"})selected.Add(id);page="library";foreach(var c in new Control[]{hero,library,hardwarePage,history,profile})c.Visible=PageControls(page).Contains(c);Filter();UpdateNavigation();}if(mode=="profile"){LicenseGate.UsePreview();RenderProfile();page="profile";foreach(var c in new Control[]{hero,library,hardwarePage,history,profile})c.Visible=PageControls(page).Contains(c);UpdateNavigation();}ShowInTaskbar=false;Opacity=0;Show();Opacity=0;LayoutApp();if(mode=="progress"){execution.Value=.64f;execution.Detail="Executando com segurança: Ajustar prioridade de jogos";execution.Visible=true;execution.BringToFront();execution.Refresh();}Application.DoEvents();using(var bmp=new Bitmap(Width,Height)){DrawToBitmap(bmp,new Rectangle(0,0,Width,Height));bmp.Save(file);}Hide();}
 public void UiTest(){selected.Clear();category="Jogos";search.Text="rust";Filter();var match=cards.Controls.OfType<ActionCard>().SingleOrDefault(c=>c.Item.id=="priorizar_rust");if(match==null||cards.Controls.OfType<ActionCard>().Any(c=>!(c.Item.title+" "+c.Item.description).ToLowerInvariant().Contains("rust")))throw new Exception("Search failed");match.Flip();if(!selected.Contains("priorizar_rust"))throw new Exception("Selection failed");category="Windows";search.Clear();Filter();if(!selected.Contains("priorizar_rust"))throw new Exception("Selection lost on category change");
  foreach(var a in catalog.actions.Where(a=>a.category==category))selected.Add(a.id);RefreshSelection();if(Chosen().Length!=catalog.actions.Count(a=>a.category==category)+1)throw new Exception("Select category failed");if(BatchPlan.Problems(Chosen()).Count==0)throw new Exception("Conflicts not detected");
  selected.Clear();search.Text="zzzzzzzz";Filter();if(run.Enabled)throw new Exception("Empty selection allowed execution");Size=new Size(980,720);LayoutApp();if(cards.Right>library.Width||footer.Bottom>ClientSize.Height)throw new Exception("Small layout overflow");Size=new Size(1380,900);category="Windows";search.Clear();Filter();}
}
